import {
  mdiAccountBadgeOutline,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiAppleKeyboardCommand,
  mdiAppleKeyboardControl,
  mdiAppleKeyboardOption,
  mdiAppleKeyboardShift,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowUp,
  mdiArrowUpBoldCircleOutline,
  mdiBackspace,
  mdiCached,
  mdiCalendar,
  mdiCancel,
  mdiChartBoxOutline,
  mdiCheck,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiCheckboxMultipleMarkedOutline,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiClose,
  mdiCloseCircle,
  mdiCloudOutline,
  mdiCloudUpload,
  mdiCloudUploadOutline,
  mdiCodeJson,
  mdiCogOutline,
  mdiCompareHorizontal,
  mdiCompassOutline,
  mdiConsole,
  mdiContentCopy,
  mdiContentSaveAlertOutline,
  mdiContentSaveCheckOutline,
  mdiContentSaveOutline,
  mdiCounter,
  mdiCpu64Bit,
  mdiDeleteOutline,
  mdiDrag,
  mdiEarth,
  mdiEyedropper,
  mdiFileDocumentOutline,
  mdiFilterCheckOutline,
  mdiFilterVariant,
  mdiFormatListBulleted,
  mdiFormatListBulletedSquare,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiGoogleCirclesCommunities,
  mdiImport,
  mdiInformation,
  mdiInformationOutline,
  mdiKeyChainVariant,
  mdiKeyOutline,
  mdiKeyPlus,
  mdiKeyRemove,
  mdiKeyboardReturn,
  mdiKeyboardSpace,
  mdiLinkOff,
  mdiLockOutline,
  mdiLogin,
  mdiLogout,
  mdiMagnify,
  mdiMenu,
  mdiMenuDown,
  mdiMenuRight,
  mdiMinus,
  mdiMinusBox,
  mdiNoteOutline,
  mdiPageFirst,
  mdiPageLast,
  mdiPalette,
  mdiPaperclip,
  mdiPause,
  mdiPencil,
  mdiPencilOutline,
  mdiPlay,
  mdiPlus,
  mdiPulse,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiShapeOutline,
  mdiShieldAccountOutline,
  mdiShieldKeyOutline,
  mdiShieldLock,
  mdiShieldLockOutline,
  mdiShieldPlusOutline,
  mdiSquareRoundedOutline,
  mdiStar,
  mdiStarCircleOutline,
  mdiStarHalfFull,
  mdiStarOutline,
  mdiSwapVertical,
  mdiTableLarge,
  mdiTagOutline,
  mdiTextBoxOutline,
  mdiTextBoxPlusOutline,
  mdiTextBoxRemoveOutline,
  mdiTextBoxSearchOutline,
  mdiUnfoldMoreHorizontal,
  mdiVectorLink,
  mdiViewDashboard,
  mdiViewDashboardOutline,
  mdiVolumeHigh,
  mdiVolumeMedium,
  mdiVolumeVariantOff,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
} from '@mdi/js'

export const mdiIconPaths: Record<string, string> = {
  'mdi-account-badge-outline': mdiAccountBadgeOutline,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-apple-keyboard-command': mdiAppleKeyboardCommand,
  'mdi-apple-keyboard-control': mdiAppleKeyboardControl,
  'mdi-apple-keyboard-option': mdiAppleKeyboardOption,
  'mdi-apple-keyboard-shift': mdiAppleKeyboardShift,
  'mdi-arrow-down': mdiArrowDown,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-up': mdiArrowUp,
  'mdi-arrow-up-bold-circle-outline': mdiArrowUpBoldCircleOutline,
  'mdi-backspace': mdiBackspace,
  'mdi-cached': mdiCached,
  'mdi-calendar': mdiCalendar,
  'mdi-cancel': mdiCancel,
  'mdi-chart-box-outline': mdiChartBoxOutline,
  'mdi-check': mdiCheck,
  'mdi-checkbox-blank-outline': mdiCheckboxBlankOutline,
  'mdi-checkbox-marked': mdiCheckboxMarked,
  'mdi-checkbox-multiple-marked-outline': mdiCheckboxMultipleMarkedOutline,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-circle': mdiCircle,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-cloud-outline': mdiCloudOutline,
  'mdi-cloud-upload': mdiCloudUpload,
  'mdi-cloud-upload-outline': mdiCloudUploadOutline,
  'mdi-code-json': mdiCodeJson,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-compare-horizontal': mdiCompareHorizontal,
  'mdi-compass-outline': mdiCompassOutline,
  'mdi-console': mdiConsole,
  'mdi-content-copy': mdiContentCopy,
  'mdi-content-save-alert-outline': mdiContentSaveAlertOutline,
  'mdi-content-save-check-outline': mdiContentSaveCheckOutline,
  'mdi-content-save-outline': mdiContentSaveOutline,
  'mdi-counter': mdiCounter,
  'mdi-cpu-64-bit': mdiCpu64Bit,
  'mdi-delete-outline': mdiDeleteOutline,
  'mdi-drag': mdiDrag,
  'mdi-earth': mdiEarth,
  'mdi-eyedropper': mdiEyedropper,
  'mdi-file-document-outline': mdiFileDocumentOutline,
  'mdi-filter-check-outline': mdiFilterCheckOutline,
  'mdi-filter-variant': mdiFilterVariant,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-format-list-bulleted-square': mdiFormatListBulletedSquare,
  'mdi-fullscreen': mdiFullscreen,
  'mdi-fullscreen-exit': mdiFullscreenExit,
  'mdi-google-circles-communities': mdiGoogleCirclesCommunities,
  'mdi-import': mdiImport,
  'mdi-information': mdiInformation,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-key-chain-variant': mdiKeyChainVariant,
  'mdi-key-outline': mdiKeyOutline,
  'mdi-key-plus': mdiKeyPlus,
  'mdi-key-remove': mdiKeyRemove,
  'mdi-keyboard-return': mdiKeyboardReturn,
  'mdi-keyboard-space': mdiKeyboardSpace,
  'mdi-link-off': mdiLinkOff,
  'mdi-lock-outline': mdiLockOutline,
  'mdi-login': mdiLogin,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-menu': mdiMenu,
  'mdi-menu-down': mdiMenuDown,
  'mdi-menu-right': mdiMenuRight,
  'mdi-minus': mdiMinus,
  'mdi-minus-box': mdiMinusBox,
  'mdi-note-outline': mdiNoteOutline,
  'mdi-page-first': mdiPageFirst,
  'mdi-page-last': mdiPageLast,
  'mdi-palette': mdiPalette,
  'mdi-paperclip': mdiPaperclip,
  'mdi-pause': mdiPause,
  'mdi-pencil': mdiPencil,
  'mdi-pencil-outline': mdiPencilOutline,
  'mdi-play': mdiPlay,
  'mdi-plus': mdiPlus,
  'mdi-pulse': mdiPulse,
  'mdi-radiobox-blank': mdiRadioboxBlank,
  'mdi-radiobox-marked': mdiRadioboxMarked,
  'mdi-shape-outline': mdiShapeOutline,
  'mdi-shield-account-outline': mdiShieldAccountOutline,
  'mdi-shield-key-outline': mdiShieldKeyOutline,
  'mdi-shield-lock': mdiShieldLock,
  'mdi-shield-lock-outline': mdiShieldLockOutline,
  'mdi-shield-plus-outline': mdiShieldPlusOutline,
  'mdi-square-rounded-outline': mdiSquareRoundedOutline,
  'mdi-star': mdiStar,
  'mdi-star-circle-outline': mdiStarCircleOutline,
  'mdi-star-half-full': mdiStarHalfFull,
  'mdi-star-outline': mdiStarOutline,
  'mdi-swap-vertical': mdiSwapVertical,
  'mdi-table-large': mdiTableLarge,
  'mdi-tag-outline': mdiTagOutline,
  'mdi-text-box-outline': mdiTextBoxOutline,
  'mdi-text-box-plus-outline': mdiTextBoxPlusOutline,
  'mdi-text-box-remove-outline': mdiTextBoxRemoveOutline,
  'mdi-text-box-search-outline': mdiTextBoxSearchOutline,
  'mdi-unfold-more-horizontal': mdiUnfoldMoreHorizontal,
  'mdi-vector-link': mdiVectorLink,
  'mdi-view-dashboard': mdiViewDashboard,
  'mdi-view-dashboard-outline': mdiViewDashboardOutline,
  'mdi-volume-high': mdiVolumeHigh,
  'mdi-volume-medium': mdiVolumeMedium,
  'mdi-volume-variant-off': mdiVolumeVariantOff,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-white-balance-sunny': mdiWhiteBalanceSunny,
}
