import {
  mdiAccountBadgeOutline,
  mdiAccountKeyOutline,
  mdiAccountSyncOutline,
  mdiAlertCircleOutline,
  mdiArrowUpBoldCircleOutline,
  mdiCached,
  mdiCashPlus,
  mdiChartBoxOutline,
  mdiCheck,
  mdiChevronDown,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiCloseCircleOutline,
  mdiCloudOutline,
  mdiCloudUploadOutline,
  mdiCodeJson,
  mdiCogOutline,
  mdiCompareHorizontal,
  mdiCompassOutline,
  mdiContentCopy,
  mdiContentSaveAlertOutline,
  mdiContentSaveCheckOutline,
  mdiContentSaveOutline,
  mdiDeleteOutline,
  mdiDrag,
  mdiFileDocumentOutline,
  mdiFilterCheckOutline,
  mdiFilterVariant,
  mdiFormatListBulleted,
  mdiImport,
  mdiInformationOutline,
  mdiKeyOutline,
  mdiKeyPlus,
  mdiKeyRemove,
  mdiKeyboardReturn,
  mdiLinkOff,
  mdiLockOutline,
  mdiLogin,
  mdiLogout,
  mdiMagnify,
  mdiMenuRight,
  mdiNoteOutline,
  mdiOpenInNew,
  mdiPencilOutline,
  mdiPlus,
  mdiPulse,
  mdiPuzzleOutline,
  mdiRefresh,
  mdiServerNetworkOutline,
  mdiShieldAccountOutline,
  mdiShieldKeyOutline,
  mdiShieldLockOutline,
  mdiShieldPlusOutline,
  mdiSquareRoundedOutline,
  mdiStarCircleOutline,
  mdiStarOutline,
  mdiSwapVertical,
  mdiTagOutline,
  mdiTextBoxOutline,
  mdiTextBoxPlusOutline,
  mdiTextBoxRemoveOutline,
  mdiTextBoxSearchOutline,
  mdiThemeLightDark,
  mdiTimerSand,
  mdiTimerOffOutline,
  mdiTuneVariant,
  mdiVectorArrangeAbove,
  mdiVectorLink,
  mdiViewDashboardOutline,
  mdiViewListOutline,
  mdiWeatherNight,
  mdiWeb,
  mdiWhiteBalanceSunny,
} from '@mdi/js'

export const mdiIconPaths: Record<string, string> = {
  'mdi-account-badge-outline': mdiAccountBadgeOutline,
  'mdi-account-key-outline': mdiAccountKeyOutline,
  'mdi-account-sync-outline': mdiAccountSyncOutline,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-arrow-up-bold-circle-outline': mdiArrowUpBoldCircleOutline,
  'mdi-cached': mdiCached,
  'mdi-cash-plus': mdiCashPlus,
  'mdi-chart-box-outline': mdiChartBoxOutline,
  'mdi-check': mdiCheck,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-close': mdiClose,
  'mdi-close-circle-outline': mdiCloseCircleOutline,
  'mdi-cloud-outline': mdiCloudOutline,
  'mdi-cloud-upload-outline': mdiCloudUploadOutline,
  'mdi-code-json': mdiCodeJson,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-compare-horizontal': mdiCompareHorizontal,
  'mdi-compass-outline': mdiCompassOutline,
  'mdi-content-copy': mdiContentCopy,
  'mdi-content-save-alert-outline': mdiContentSaveAlertOutline,
  'mdi-content-save-check-outline': mdiContentSaveCheckOutline,
  'mdi-content-save-outline': mdiContentSaveOutline,
  'mdi-delete-outline': mdiDeleteOutline,
  'mdi-drag': mdiDrag,
  'mdi-file-document-outline': mdiFileDocumentOutline,
  'mdi-filter-check-outline': mdiFilterCheckOutline,
  'mdi-filter-variant': mdiFilterVariant,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-import': mdiImport,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-key-outline': mdiKeyOutline,
  'mdi-key-plus': mdiKeyPlus,
  'mdi-key-remove': mdiKeyRemove,
  'mdi-keyboard-return': mdiKeyboardReturn,
  'mdi-link-off': mdiLinkOff,
  'mdi-lock-outline': mdiLockOutline,
  'mdi-login': mdiLogin,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-menu-right': mdiMenuRight,
  'mdi-note-outline': mdiNoteOutline,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-pencil-outline': mdiPencilOutline,
  'mdi-plus': mdiPlus,
  'mdi-pulse': mdiPulse,
  'mdi-puzzle-outline': mdiPuzzleOutline,
  'mdi-refresh': mdiRefresh,
  'mdi-server-network-outline': mdiServerNetworkOutline,
  'mdi-shield-account-outline': mdiShieldAccountOutline,
  'mdi-shield-key-outline': mdiShieldKeyOutline,
  'mdi-shield-lock-outline': mdiShieldLockOutline,
  'mdi-shield-plus-outline': mdiShieldPlusOutline,
  'mdi-square-rounded-outline': mdiSquareRoundedOutline,
  'mdi-star-circle-outline': mdiStarCircleOutline,
  'mdi-star-outline': mdiStarOutline,
  'mdi-swap-vertical': mdiSwapVertical,
  'mdi-tag-outline': mdiTagOutline,
  'mdi-text-box-outline': mdiTextBoxOutline,
  'mdi-text-box-plus-outline': mdiTextBoxPlusOutline,
  'mdi-text-box-remove-outline': mdiTextBoxRemoveOutline,
  'mdi-text-box-search-outline': mdiTextBoxSearchOutline,
  'mdi-theme-light-dark': mdiThemeLightDark,
  'mdi-timer-sand': mdiTimerSand,
  'mdi-timer-off-outline': mdiTimerOffOutline,
  'mdi-tune-variant': mdiTuneVariant,
  'mdi-vector-arrange-above': mdiVectorArrangeAbove,
  'mdi-vector-link': mdiVectorLink,
  'mdi-view-dashboard-outline': mdiViewDashboardOutline,
  'mdi-view-list-outline': mdiViewListOutline,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-web': mdiWeb,
  'mdi-white-balance-sunny': mdiWhiteBalanceSunny,
}

/**
 * provider 品牌图标 path,构建期由 build/lobe-icons.plugin.mjs 从
 * @lobehub/icons 各图标 Mono 变体(currentColor 单剪影、viewBox 0 0 24 24)
 * 抽取,经虚拟模块 virtual:lobe-icons 注入。随主题单色渲染,与 mdi outline 协调。
 */
export interface LobeIconPath {
  d: string
  evenodd?: boolean
}

// 虚拟模块无类型声明,这里显式标注
// @ts-expect-error 由 vite 虚拟模块提供
import { lobeIconPaths as lobeIconPathsData } from 'virtual:lobe-icons'

export const lobeIconPaths: Record<string, LobeIconPath[]> = lobeIconPathsData
