ALTER TABLE codex_quota
    ADD COLUMN IF NOT EXISTS quota_1mo FLOAT NOT NULL DEFAULT 1.0,
    ADD COLUMN IF NOT EXISTS reset_1mo TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS quota_spark_1mo FLOAT NOT NULL DEFAULT 1.0,
    ADD COLUMN IF NOT EXISTS reset_spark_1mo TIMESTAMPTZ;
