// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: antigravity_quota.sql

package sqlite

import (
	"context"
)

const deleteAntigravityQuota = `-- name: DeleteAntigravityQuota :execrows
DELETE FROM antigravity_quota WHERE credential_id = ?
`

func (q *Queries) DeleteAntigravityQuota(ctx context.Context, credentialID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAntigravityQuota, credentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAvailableAntigravity = `-- name: ListAvailableAntigravity :many
SELECT
    a.id,
    a.email,
    a.project_id,
    a.plan_type,
    COALESCE(q.quota_claude, 1.0) AS quota_claude,
    COALESCE(q.reset_claude, datetime('now')) AS reset_claude,
    COALESCE(q.quota_pro, 1.0) AS quota_pro,
    COALESCE(q.reset_pro, datetime('now')) AS reset_pro,
    COALESCE(q.quota_flash, 1.0) AS quota_flash,
    COALESCE(q.reset_flash, datetime('now')) AS reset_flash,
    COALESCE(q.quota_flashlite, 1.0) AS quota_flashlite,
    COALESCE(q.reset_flashlite, datetime('now')) AS reset_flashlite,
    COALESCE(q.quota_tab, 1.0) AS quota_tab,
    COALESCE(q.reset_tab, datetime('now', '+100 years')) AS reset_tab,
    COALESCE(q.quota_image, 1.0) AS quota_image,
    COALESCE(q.reset_image, datetime('now')) AS reset_image,
    COALESCE(c.credits_amount, 0) AS credits_amount,
    COALESCE(c.credit_types, '') AS credit_types,
    COALESCE(q.throttled_until_claude, datetime('now')) AS throttled_until_claude,
    COALESCE(q.throttled_until_pro, datetime('now')) AS throttled_until_pro,
    COALESCE(q.throttled_until_flash, datetime('now')) AS throttled_until_flash,
    COALESCE(q.throttled_until_flashlite, datetime('now')) AS throttled_until_flashlite,
    COALESCE(q.throttled_until_tab, datetime('now')) AS throttled_until_tab,
    COALESCE(q.throttled_until_image, datetime('now')) AS throttled_until_image,
    CAST(max(
        COALESCE(q.throttled_until_claude, datetime('now')),
        COALESCE(q.throttled_until_pro, datetime('now')),
        COALESCE(q.throttled_until_flash, datetime('now')),
        COALESCE(q.throttled_until_flashlite, datetime('now')),
        COALESCE(q.throttled_until_tab, datetime('now')),
        COALESCE(q.throttled_until_image, datetime('now'))
    ) AS TEXT) AS throttled_until,
    COALESCE(q.synced_at, '') AS synced_at
FROM antigravity a
LEFT JOIN antigravity_quota q ON q.credential_id = a.id
LEFT JOIN antigravity_credits c ON c.credential_id = a.id
WHERE a.status = 'enabled'
  AND (a.expired > datetime('now') OR a.refresh_token != '')
ORDER BY
    COALESCE(q.quota_claude, 1.0) DESC,
    COALESCE(q.quota_pro, 1.0) DESC,
    COALESCE(q.quota_flash, 1.0) DESC,
    COALESCE(q.quota_flashlite, 1.0) DESC,
    COALESCE(q.quota_tab, 1.0) DESC,
    COALESCE(q.quota_image, 1.0) DESC
`

type ListAvailableAntigravityRow struct {
	ID                      string  `json:"id"`
	Email                   string  `json:"email"`
	ProjectID               string  `json:"project_id"`
	PlanType                string  `json:"plan_type"`
	QuotaClaude             float64 `json:"quota_claude"`
	ResetClaude             string  `json:"reset_claude"`
	QuotaPro                float64 `json:"quota_pro"`
	ResetPro                string  `json:"reset_pro"`
	QuotaFlash              float64 `json:"quota_flash"`
	ResetFlash              string  `json:"reset_flash"`
	QuotaFlashlite          float64 `json:"quota_flashlite"`
	ResetFlashlite          string  `json:"reset_flashlite"`
	QuotaTab                float64 `json:"quota_tab"`
	ResetTab                string  `json:"reset_tab"`
	QuotaImage              float64 `json:"quota_image"`
	ResetImage              string  `json:"reset_image"`
	CreditsAmount           float64 `json:"credits_amount"`
	CreditTypes             string  `json:"credit_types"`
	ThrottledUntilClaude    string  `json:"throttled_until_claude"`
	ThrottledUntilPro       string  `json:"throttled_until_pro"`
	ThrottledUntilFlash     string  `json:"throttled_until_flash"`
	ThrottledUntilFlashlite string  `json:"throttled_until_flashlite"`
	ThrottledUntilTab       string  `json:"throttled_until_tab"`
	ThrottledUntilImage     string  `json:"throttled_until_image"`
	ThrottledUntil          string  `json:"throttled_until"`
	SyncedAt                string  `json:"synced_at"`
}

func (q *Queries) ListAvailableAntigravity(ctx context.Context) ([]ListAvailableAntigravityRow, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableAntigravity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableAntigravityRow{}
	for rows.Next() {
		var i ListAvailableAntigravityRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ProjectID,
			&i.PlanType,
			&i.QuotaClaude,
			&i.ResetClaude,
			&i.QuotaPro,
			&i.ResetPro,
			&i.QuotaFlash,
			&i.ResetFlash,
			&i.QuotaFlashlite,
			&i.ResetFlashlite,
			&i.QuotaTab,
			&i.ResetTab,
			&i.QuotaImage,
			&i.ResetImage,
			&i.CreditsAmount,
			&i.CreditTypes,
			&i.ThrottledUntilClaude,
			&i.ThrottledUntilPro,
			&i.ThrottledUntilFlash,
			&i.ThrottledUntilFlashlite,
			&i.ThrottledUntilTab,
			&i.ThrottledUntilImage,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAntigravityQuotaThrottledAll = `-- name: SetAntigravityQuotaThrottledAll :exec
INSERT INTO antigravity_quota (
    credential_id,
    throttled_until_claude,
    throttled_until_pro,
    throttled_until_flash,
    throttled_until_flashlite,
    throttled_until_tab,
    throttled_until_image,
    synced_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_claude = excluded.throttled_until_claude,
    throttled_until_pro = excluded.throttled_until_pro,
    throttled_until_flash = excluded.throttled_until_flash,
    throttled_until_flashlite = excluded.throttled_until_flashlite,
    throttled_until_tab = excluded.throttled_until_tab,
    throttled_until_image = excluded.throttled_until_image,
    synced_at = datetime('now')
`

type SetAntigravityQuotaThrottledAllParams struct {
	CredentialID            string `json:"credential_id"`
	ThrottledUntilClaude    string `json:"throttled_until_claude"`
	ThrottledUntilPro       string `json:"throttled_until_pro"`
	ThrottledUntilFlash     string `json:"throttled_until_flash"`
	ThrottledUntilFlashlite string `json:"throttled_until_flashlite"`
	ThrottledUntilTab       string `json:"throttled_until_tab"`
	ThrottledUntilImage     string `json:"throttled_until_image"`
}

func (q *Queries) SetAntigravityQuotaThrottledAll(ctx context.Context, arg SetAntigravityQuotaThrottledAllParams) error {
	_, err := q.db.ExecContext(ctx, setAntigravityQuotaThrottledAll,
		arg.CredentialID,
		arg.ThrottledUntilClaude,
		arg.ThrottledUntilPro,
		arg.ThrottledUntilFlash,
		arg.ThrottledUntilFlashlite,
		arg.ThrottledUntilTab,
		arg.ThrottledUntilImage,
	)
	return err
}

const setAntigravityQuotaThrottledClaude = `-- name: SetAntigravityQuotaThrottledClaude :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_claude, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_claude = excluded.throttled_until_claude,
    synced_at = datetime('now')
`

type SetAntigravityQuotaThrottledClaudeParams struct {
	CredentialID         string `json:"credential_id"`
	ThrottledUntilClaude string `json:"throttled_until_claude"`
}

func (q *Queries) SetAntigravityQuotaThrottledClaude(ctx context.Context, arg SetAntigravityQuotaThrottledClaudeParams) error {
	_, err := q.db.ExecContext(ctx, setAntigravityQuotaThrottledClaude, arg.CredentialID, arg.ThrottledUntilClaude)
	return err
}

const setAntigravityQuotaThrottledFlash = `-- name: SetAntigravityQuotaThrottledFlash :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_flash, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_flash = excluded.throttled_until_flash,
    synced_at = datetime('now')
`

type SetAntigravityQuotaThrottledFlashParams struct {
	CredentialID        string `json:"credential_id"`
	ThrottledUntilFlash string `json:"throttled_until_flash"`
}

func (q *Queries) SetAntigravityQuotaThrottledFlash(ctx context.Context, arg SetAntigravityQuotaThrottledFlashParams) error {
	_, err := q.db.ExecContext(ctx, setAntigravityQuotaThrottledFlash, arg.CredentialID, arg.ThrottledUntilFlash)
	return err
}

const setAntigravityQuotaThrottledFlashLite = `-- name: SetAntigravityQuotaThrottledFlashLite :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_flashlite, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_flashlite = excluded.throttled_until_flashlite,
    synced_at = datetime('now')
`

type SetAntigravityQuotaThrottledFlashLiteParams struct {
	CredentialID            string `json:"credential_id"`
	ThrottledUntilFlashlite string `json:"throttled_until_flashlite"`
}

func (q *Queries) SetAntigravityQuotaThrottledFlashLite(ctx context.Context, arg SetAntigravityQuotaThrottledFlashLiteParams) error {
	_, err := q.db.ExecContext(ctx, setAntigravityQuotaThrottledFlashLite, arg.CredentialID, arg.ThrottledUntilFlashlite)
	return err
}

const setAntigravityQuotaThrottledImage = `-- name: SetAntigravityQuotaThrottledImage :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_image, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_image = excluded.throttled_until_image,
    synced_at = datetime('now')
`

type SetAntigravityQuotaThrottledImageParams struct {
	CredentialID        string `json:"credential_id"`
	ThrottledUntilImage string `json:"throttled_until_image"`
}

func (q *Queries) SetAntigravityQuotaThrottledImage(ctx context.Context, arg SetAntigravityQuotaThrottledImageParams) error {
	_, err := q.db.ExecContext(ctx, setAntigravityQuotaThrottledImage, arg.CredentialID, arg.ThrottledUntilImage)
	return err
}

const setAntigravityQuotaThrottledPro = `-- name: SetAntigravityQuotaThrottledPro :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_pro, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_pro = excluded.throttled_until_pro,
    synced_at = datetime('now')
`

type SetAntigravityQuotaThrottledProParams struct {
	CredentialID      string `json:"credential_id"`
	ThrottledUntilPro string `json:"throttled_until_pro"`
}

func (q *Queries) SetAntigravityQuotaThrottledPro(ctx context.Context, arg SetAntigravityQuotaThrottledProParams) error {
	_, err := q.db.ExecContext(ctx, setAntigravityQuotaThrottledPro, arg.CredentialID, arg.ThrottledUntilPro)
	return err
}

const setAntigravityQuotaThrottledTab = `-- name: SetAntigravityQuotaThrottledTab :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_tab, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_tab = excluded.throttled_until_tab,
    synced_at = datetime('now')
`

type SetAntigravityQuotaThrottledTabParams struct {
	CredentialID      string `json:"credential_id"`
	ThrottledUntilTab string `json:"throttled_until_tab"`
}

func (q *Queries) SetAntigravityQuotaThrottledTab(ctx context.Context, arg SetAntigravityQuotaThrottledTabParams) error {
	_, err := q.db.ExecContext(ctx, setAntigravityQuotaThrottledTab, arg.CredentialID, arg.ThrottledUntilTab)
	return err
}

const upsertAntigravityQuota = `-- name: UpsertAntigravityQuota :one
INSERT INTO antigravity_quota (
    credential_id,
    quota_claude, reset_claude,
    quota_pro, reset_pro,
    quota_flash, reset_flash,
    quota_flashlite, reset_flashlite,
    quota_tab, reset_tab,
    quota_image, reset_image,
    synced_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    quota_claude = excluded.quota_claude,
    reset_claude = excluded.reset_claude,
    quota_pro = excluded.quota_pro,
    reset_pro = excluded.reset_pro,
    quota_flash = excluded.quota_flash,
    reset_flash = excluded.reset_flash,
    quota_flashlite = excluded.quota_flashlite,
    reset_flashlite = excluded.reset_flashlite,
    quota_tab = excluded.quota_tab,
    reset_tab = excluded.reset_tab,
    quota_image = excluded.quota_image,
    reset_image = excluded.reset_image,
    synced_at = datetime('now')
RETURNING credential_id, quota_claude, reset_claude, quota_pro, reset_pro, quota_flash, reset_flash, quota_flashlite, reset_flashlite, quota_tab, reset_tab, quota_image, reset_image, throttled_until_claude, throttled_until_pro, throttled_until_flash, throttled_until_flashlite, throttled_until_tab, throttled_until_image, synced_at
`

type UpsertAntigravityQuotaParams struct {
	CredentialID   string  `json:"credential_id"`
	QuotaClaude    float64 `json:"quota_claude"`
	ResetClaude    string  `json:"reset_claude"`
	QuotaPro       float64 `json:"quota_pro"`
	ResetPro       string  `json:"reset_pro"`
	QuotaFlash     float64 `json:"quota_flash"`
	ResetFlash     string  `json:"reset_flash"`
	QuotaFlashlite float64 `json:"quota_flashlite"`
	ResetFlashlite string  `json:"reset_flashlite"`
	QuotaTab       float64 `json:"quota_tab"`
	ResetTab       string  `json:"reset_tab"`
	QuotaImage     float64 `json:"quota_image"`
	ResetImage     string  `json:"reset_image"`
}

func (q *Queries) UpsertAntigravityQuota(ctx context.Context, arg UpsertAntigravityQuotaParams) (AntigravityQuotum, error) {
	row := q.db.QueryRowContext(ctx, upsertAntigravityQuota,
		arg.CredentialID,
		arg.QuotaClaude,
		arg.ResetClaude,
		arg.QuotaPro,
		arg.ResetPro,
		arg.QuotaFlash,
		arg.ResetFlash,
		arg.QuotaFlashlite,
		arg.ResetFlashlite,
		arg.QuotaTab,
		arg.ResetTab,
		arg.QuotaImage,
		arg.ResetImage,
	)
	var i AntigravityQuotum
	err := row.Scan(
		&i.CredentialID,
		&i.QuotaClaude,
		&i.ResetClaude,
		&i.QuotaPro,
		&i.ResetPro,
		&i.QuotaFlash,
		&i.ResetFlash,
		&i.QuotaFlashlite,
		&i.ResetFlashlite,
		&i.QuotaTab,
		&i.ResetTab,
		&i.QuotaImage,
		&i.ResetImage,
		&i.ThrottledUntilClaude,
		&i.ThrottledUntilPro,
		&i.ThrottledUntilFlash,
		&i.ThrottledUntilFlashlite,
		&i.ThrottledUntilTab,
		&i.ThrottledUntilImage,
		&i.SyncedAt,
	)
	return i, err
}
