// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: antigravity.sql

package sqlite

import (
	"context"
)

const countAntigravity = `-- name: CountAntigravity :one
SELECT COUNT(*) FROM antigravity
`

func (q *Queries) CountAntigravity(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAntigravity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAntigravityFiltered = `-- name: CountAntigravityFiltered :one
SELECT COUNT(*)
FROM antigravity a
LEFT JOIN antigravity_quota q ON q.credential_id = a.id
WHERE
    (?1 = '' OR LOWER(a.id) LIKE ?1 OR LOWER(a.email) LIKE ?1 OR LOWER(a.status) LIKE ?1 OR LOWER(a.plan_type) LIKE ?1)
    AND (?2 = '' OR a.status = ?2)
    AND (?3 = '' OR LOWER(a.plan_type) = LOWER(?3))
    AND (?4 = 0 OR q.synced_at IS NULL OR q.synced_at = '')
`

type CountAntigravityFilteredParams struct {
	Search       interface{} `json:"search"`
	Status       interface{} `json:"status"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
}

func (q *Queries) CountAntigravityFiltered(ctx context.Context, arg CountAntigravityFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAntigravityFiltered,
		arg.Search,
		arg.Status,
		arg.PlanType,
		arg.UnsyncedOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledAntigravity = `-- name: CountEnabledAntigravity :one
SELECT COUNT(*)
FROM antigravity
WHERE status = 'enabled'
`

func (q *Queries) CountEnabledAntigravity(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledAntigravity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAntigravity = `-- name: DeleteAntigravity :execrows
DELETE FROM antigravity WHERE id = ?
`

func (q *Queries) DeleteAntigravity(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAntigravity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAntigravity = `-- name: GetAntigravity :one
SELECT id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
FROM antigravity
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAntigravity(ctx context.Context, id string) (Antigravity, error) {
	row := q.db.QueryRowContext(ctx, getAntigravity, id)
	var i Antigravity
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const listAntigravityPaged = `-- name: ListAntigravityPaged :many
SELECT
    a.id, a.status, a.access_token, a.refresh_token, a.expired,
    a.email, a.project_id, a.plan_type, a.reason,
    COALESCE(q.quota_claude, 1.0) AS quota_claude,
    COALESCE(q.reset_claude, datetime('now')) AS reset_claude,
    COALESCE(q.quota_pro, 1.0) AS quota_pro,
    COALESCE(q.reset_pro, datetime('now')) AS reset_pro,
    COALESCE(q.quota_flash, 1.0) AS quota_flash,
    COALESCE(q.reset_flash, datetime('now')) AS reset_flash,
    COALESCE(q.quota_flashlite, 1.0) AS quota_flashlite,
    COALESCE(q.reset_flashlite, datetime('now')) AS reset_flashlite,
    COALESCE(q.quota_tab, 1.0) AS quota_tab,
    COALESCE(q.reset_tab, datetime('now', '+100 years')) AS reset_tab,
    COALESCE(q.quota_image, 1.0) AS quota_image,
    COALESCE(q.reset_image, datetime('now')) AS reset_image,
    COALESCE(c.credits_amount, 0) AS credits_amount,
    COALESCE(c.credit_types, '') AS credit_types,
    CAST(max(
        COALESCE(q.throttled_until_claude, datetime('now')),
        COALESCE(q.throttled_until_pro, datetime('now')),
        COALESCE(q.throttled_until_flash, datetime('now')),
        COALESCE(q.throttled_until_flashlite, datetime('now')),
        COALESCE(q.throttled_until_tab, datetime('now')),
        COALESCE(q.throttled_until_image, datetime('now'))
    ) AS TEXT) AS throttled_until,
    COALESCE(q.synced_at, '') AS synced_at
FROM antigravity a
LEFT JOIN antigravity_quota q ON q.credential_id = a.id
LEFT JOIN antigravity_credits c ON c.credential_id = a.id
WHERE
    (?1 = '' OR LOWER(a.id) LIKE ?1 OR LOWER(a.email) LIKE ?1 OR LOWER(a.status) LIKE ?1 OR LOWER(a.plan_type) LIKE ?1)
    AND (?2 = '' OR a.status = ?2)
    AND (?3 = '' OR LOWER(a.plan_type) = LOWER(?3))
    AND (?4 = 0 OR q.synced_at IS NULL OR q.synced_at = '')
ORDER BY a.id
LIMIT ?6 OFFSET ?5
`

type ListAntigravityPagedParams struct {
	Search       interface{} `json:"search"`
	Status       interface{} `json:"status"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
	PageOffset   int64       `json:"page_offset"`
	PageLimit    int64       `json:"page_limit"`
}

type ListAntigravityPagedRow struct {
	ID             string  `json:"id"`
	Status         string  `json:"status"`
	AccessToken    string  `json:"access_token"`
	RefreshToken   string  `json:"refresh_token"`
	Expired        string  `json:"expired"`
	Email          string  `json:"email"`
	ProjectID      string  `json:"project_id"`
	PlanType       string  `json:"plan_type"`
	Reason         string  `json:"reason"`
	QuotaClaude    float64 `json:"quota_claude"`
	ResetClaude    string  `json:"reset_claude"`
	QuotaPro       float64 `json:"quota_pro"`
	ResetPro       string  `json:"reset_pro"`
	QuotaFlash     float64 `json:"quota_flash"`
	ResetFlash     string  `json:"reset_flash"`
	QuotaFlashlite float64 `json:"quota_flashlite"`
	ResetFlashlite string  `json:"reset_flashlite"`
	QuotaTab       float64 `json:"quota_tab"`
	ResetTab       string  `json:"reset_tab"`
	QuotaImage     float64 `json:"quota_image"`
	ResetImage     string  `json:"reset_image"`
	CreditsAmount  float64 `json:"credits_amount"`
	CreditTypes    string  `json:"credit_types"`
	ThrottledUntil string  `json:"throttled_until"`
	SyncedAt       string  `json:"synced_at"`
}

func (q *Queries) ListAntigravityPaged(ctx context.Context, arg ListAntigravityPagedParams) ([]ListAntigravityPagedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAntigravityPaged,
		arg.Search,
		arg.Status,
		arg.PlanType,
		arg.UnsyncedOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAntigravityPagedRow{}
	for rows.Next() {
		var i ListAntigravityPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Expired,
			&i.Email,
			&i.ProjectID,
			&i.PlanType,
			&i.Reason,
			&i.QuotaClaude,
			&i.ResetClaude,
			&i.QuotaPro,
			&i.ResetPro,
			&i.QuotaFlash,
			&i.ResetFlash,
			&i.QuotaFlashlite,
			&i.ResetFlashlite,
			&i.QuotaTab,
			&i.ResetTab,
			&i.QuotaImage,
			&i.ResetImage,
			&i.CreditsAmount,
			&i.CreditTypes,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAntigravityStatus = `-- name: UpdateAntigravityStatus :one
UPDATE antigravity
SET status = ?, reason = ?
WHERE id = ?
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpdateAntigravityStatusParams struct {
	Status string `json:"status"`
	Reason string `json:"reason"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateAntigravityStatus(ctx context.Context, arg UpdateAntigravityStatusParams) (Antigravity, error) {
	row := q.db.QueryRowContext(ctx, updateAntigravityStatus, arg.Status, arg.Reason, arg.ID)
	var i Antigravity
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const updateAntigravityTokens = `-- name: UpdateAntigravityTokens :one
UPDATE antigravity
SET
    status = ?,
    access_token = ?,
    refresh_token = ?,
    expired = ?,
    email = ?,
    project_id = ?,
    plan_type = ?,
    reason = '',
    synced_at = datetime('now')
WHERE id = ?
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpdateAntigravityTokensParams struct {
	Status       string `json:"status"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	Expired      string `json:"expired"`
	Email        string `json:"email"`
	ProjectID    string `json:"project_id"`
	PlanType     string `json:"plan_type"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateAntigravityTokens(ctx context.Context, arg UpdateAntigravityTokensParams) (Antigravity, error) {
	row := q.db.QueryRowContext(ctx, updateAntigravityTokens,
		arg.Status,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expired,
		arg.Email,
		arg.ProjectID,
		arg.PlanType,
		arg.ID,
	)
	var i Antigravity
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const upsertAntigravity = `-- name: UpsertAntigravity :one
INSERT INTO antigravity (id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT (id) DO UPDATE
SET
    status = EXCLUDED.status,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expired = EXCLUDED.expired,
    email = EXCLUDED.email,
    project_id = EXCLUDED.project_id,
    plan_type = EXCLUDED.plan_type,
    reason = EXCLUDED.reason,
    synced_at = datetime('now')
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpsertAntigravityParams struct {
	ID           string `json:"id"`
	Status       string `json:"status"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	Expired      string `json:"expired"`
	Email        string `json:"email"`
	ProjectID    string `json:"project_id"`
	PlanType     string `json:"plan_type"`
	Reason       string `json:"reason"`
}

func (q *Queries) UpsertAntigravity(ctx context.Context, arg UpsertAntigravityParams) (Antigravity, error) {
	row := q.db.QueryRowContext(ctx, upsertAntigravity,
		arg.ID,
		arg.Status,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expired,
		arg.Email,
		arg.ProjectID,
		arg.PlanType,
		arg.Reason,
	)
	var i Antigravity
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}
