// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: antigravity_credits.sql

package sqlite

import (
	"context"
)

const getAntigravityCredits = `-- name: GetAntigravityCredits :one
SELECT credential_id, credits_amount, credit_types, synced_at FROM antigravity_credits WHERE credential_id = ? LIMIT 1
`

func (q *Queries) GetAntigravityCredits(ctx context.Context, credentialID string) (AntigravityCredit, error) {
	row := q.db.QueryRowContext(ctx, getAntigravityCredits, credentialID)
	var i AntigravityCredit
	err := row.Scan(
		&i.CredentialID,
		&i.CreditsAmount,
		&i.CreditTypes,
		&i.SyncedAt,
	)
	return i, err
}

const upsertAntigravityCredits = `-- name: UpsertAntigravityCredits :one
INSERT INTO antigravity_credits (credential_id, credits_amount, credit_types, synced_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    credits_amount = excluded.credits_amount,
    credit_types = excluded.credit_types,
    synced_at = datetime('now')
RETURNING credential_id, credits_amount, credit_types, synced_at
`

type UpsertAntigravityCreditsParams struct {
	CredentialID  string  `json:"credential_id"`
	CreditsAmount float64 `json:"credits_amount"`
	CreditTypes   string  `json:"credit_types"`
}

func (q *Queries) UpsertAntigravityCredits(ctx context.Context, arg UpsertAntigravityCreditsParams) (AntigravityCredit, error) {
	row := q.db.QueryRowContext(ctx, upsertAntigravityCredits, arg.CredentialID, arg.CreditsAmount, arg.CreditTypes)
	var i AntigravityCredit
	err := row.Scan(
		&i.CredentialID,
		&i.CreditsAmount,
		&i.CreditTypes,
		&i.SyncedAt,
	)
	return i, err
}
