// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_keys.sql

package sqlite

import (
	"context"
)

const countAuthKeys = `-- name: CountAuthKeys :one
SELECT COUNT(*) FROM auth_keys
`

func (q *Queries) CountAuthKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuthKeysByRole = `-- name: CountAuthKeysByRole :one
SELECT COUNT(*) FROM auth_keys WHERE role = ?
`

func (q *Queries) CountAuthKeysByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthKeysByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthKey = `-- name: CreateAuthKey :one
INSERT INTO auth_keys (key, role, note) VALUES (?, ?, ?) RETURNING key, role, note, created_at
`

type CreateAuthKeyParams struct {
	Key  string `json:"key"`
	Role string `json:"role"`
	Note string `json:"note"`
}

func (q *Queries) CreateAuthKey(ctx context.Context, arg CreateAuthKeyParams) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, createAuthKey, arg.Key, arg.Role, arg.Note)
	var i AuthKey
	err := row.Scan(
		&i.Key,
		&i.Role,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthKey = `-- name: DeleteAuthKey :execrows
DELETE FROM auth_keys WHERE key = ?
`

func (q *Queries) DeleteAuthKey(ctx context.Context, key string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuthKey, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAuthKey = `-- name: GetAuthKey :one
SELECT key, role, note, created_at FROM auth_keys WHERE key = ?
`

func (q *Queries) GetAuthKey(ctx context.Context, key string) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, getAuthKey, key)
	var i AuthKey
	err := row.Scan(
		&i.Key,
		&i.Role,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthKeys = `-- name: ListAuthKeys :many
SELECT key, role, note, created_at FROM auth_keys ORDER BY created_at
`

func (q *Queries) ListAuthKeys(ctx context.Context) ([]AuthKey, error) {
	rows, err := q.db.QueryContext(ctx, listAuthKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthKey{}
	for rows.Next() {
		var i AuthKey
		if err := rows.Scan(
			&i.Key,
			&i.Role,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthKey = `-- name: UpdateAuthKey :one
UPDATE auth_keys
SET role = ?, note = ?
WHERE key = ?
RETURNING key, role, note, created_at
`

type UpdateAuthKeyParams struct {
	Role string `json:"role"`
	Note string `json:"note"`
	Key  string `json:"key"`
}

func (q *Queries) UpdateAuthKey(ctx context.Context, arg UpdateAuthKeyParams) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, updateAuthKey, arg.Role, arg.Note, arg.Key)
	var i AuthKey
	err := row.Scan(
		&i.Key,
		&i.Role,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
