// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: codex.sql

package sqlite

import (
	"context"
)

const countCodex = `-- name: CountCodex :one
SELECT COUNT(*) FROM codex
`

func (q *Queries) CountCodex(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCodex)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCodexFiltered = `-- name: CountCodexFiltered :one
SELECT COUNT(*)
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
WHERE
    (?1 = '' OR LOWER(c.id) LIKE ?1 OR LOWER(c.status) LIKE ?1 OR LOWER(c.plan_type) LIKE ?1)
    AND (?2 = '' OR c.status = ?2)
    AND (?3 = '' OR LOWER(c.plan_type) = LOWER(?3))
    AND (?4 = 0 OR q.synced_at IS NULL OR q.synced_at = '')
`

type CountCodexFilteredParams struct {
	Search       interface{} `json:"search"`
	Status       interface{} `json:"status"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
}

func (q *Queries) CountCodexFiltered(ctx context.Context, arg CountCodexFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCodexFiltered,
		arg.Search,
		arg.Status,
		arg.PlanType,
		arg.UnsyncedOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledCodex = `-- name: CountEnabledCodex :one
SELECT COUNT(*)
FROM codex
WHERE status = 'enabled'
`

func (q *Queries) CountEnabledCodex(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledCodex)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCodex = `-- name: CreateCodex :one
INSERT INTO codex (id, status, access_token, expired, refresh_token, plan_type)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type CreateCodexParams struct {
	ID           string `json:"id"`
	Status       string `json:"status"`
	AccessToken  string `json:"access_token"`
	Expired      string `json:"expired"`
	RefreshToken string `json:"refresh_token"`
	PlanType     string `json:"plan_type"`
}

func (q *Queries) CreateCodex(ctx context.Context, arg CreateCodexParams) (Codex, error) {
	row := q.db.QueryRowContext(ctx, createCodex,
		arg.ID,
		arg.Status,
		arg.AccessToken,
		arg.Expired,
		arg.RefreshToken,
		arg.PlanType,
	)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const deleteCodex = `-- name: DeleteCodex :execrows
DELETE FROM codex WHERE id = ?
`

func (q *Queries) DeleteCodex(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCodex, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCodex = `-- name: GetCodex :one
SELECT id, status, access_token, expired, refresh_token, plan_type, reason
FROM codex
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCodex(ctx context.Context, id string) (Codex, error) {
	row := q.db.QueryRowContext(ctx, getCodex, id)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const listCodex = `-- name: ListCodex :many
SELECT
    c.id, c.status, c.access_token, c.expired, c.refresh_token, c.plan_type, c.reason,
    COALESCE(q.quota_5h, 1.0) AS quota_5h,
    COALESCE(q.quota_7d, 1.0) AS quota_7d,
    COALESCE(q.quota_spark_5h, 1.0) AS quota_spark_5h,
    COALESCE(q.quota_spark_7d, 1.0) AS quota_spark_7d,
    COALESCE(q.reset_5h, '') AS reset_5h,
    COALESCE(q.reset_7d, '') AS reset_7d,
    COALESCE(q.reset_spark_5h, '') AS reset_spark_5h,
    COALESCE(q.reset_spark_7d, '') AS reset_spark_7d,
    CAST(max(COALESCE(q.throttled_until, ''), COALESCE(q.throttled_until_spark, '')) AS TEXT) AS throttled_until,
    COALESCE(q.synced_at, '') AS synced_at
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
ORDER BY c.id
`

type ListCodexRow struct {
	ID             string  `json:"id"`
	Status         string  `json:"status"`
	AccessToken    string  `json:"access_token"`
	Expired        string  `json:"expired"`
	RefreshToken   string  `json:"refresh_token"`
	PlanType       string  `json:"plan_type"`
	Reason         string  `json:"reason"`
	Quota5h        float64 `json:"quota_5h"`
	Quota7d        float64 `json:"quota_7d"`
	QuotaSpark5h   float64 `json:"quota_spark_5h"`
	QuotaSpark7d   float64 `json:"quota_spark_7d"`
	Reset5h        string  `json:"reset_5h"`
	Reset7d        string  `json:"reset_7d"`
	ResetSpark5h   string  `json:"reset_spark_5h"`
	ResetSpark7d   string  `json:"reset_spark_7d"`
	ThrottledUntil string  `json:"throttled_until"`
	SyncedAt       string  `json:"synced_at"`
}

func (q *Queries) ListCodex(ctx context.Context) ([]ListCodexRow, error) {
	rows, err := q.db.QueryContext(ctx, listCodex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCodexRow{}
	for rows.Next() {
		var i ListCodexRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.Expired,
			&i.RefreshToken,
			&i.PlanType,
			&i.Reason,
			&i.Quota5h,
			&i.Quota7d,
			&i.QuotaSpark5h,
			&i.QuotaSpark7d,
			&i.Reset5h,
			&i.Reset7d,
			&i.ResetSpark5h,
			&i.ResetSpark7d,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodexPaged = `-- name: ListCodexPaged :many
SELECT
    c.id, c.status, c.access_token, c.expired, c.refresh_token, c.plan_type, c.reason,
    COALESCE(q.quota_5h, 1.0) AS quota_5h,
    COALESCE(q.quota_7d, 1.0) AS quota_7d,
    COALESCE(q.quota_spark_5h, 1.0) AS quota_spark_5h,
    COALESCE(q.quota_spark_7d, 1.0) AS quota_spark_7d,
    COALESCE(q.reset_5h, '') AS reset_5h,
    COALESCE(q.reset_7d, '') AS reset_7d,
    COALESCE(q.reset_spark_5h, '') AS reset_spark_5h,
    COALESCE(q.reset_spark_7d, '') AS reset_spark_7d,
    CAST(max(COALESCE(q.throttled_until, ''), COALESCE(q.throttled_until_spark, '')) AS TEXT) AS throttled_until,
    COALESCE(q.synced_at, '') AS synced_at
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
WHERE
    (?1 = '' OR LOWER(c.id) LIKE ?1 OR LOWER(c.status) LIKE ?1 OR LOWER(c.plan_type) LIKE ?1)
    AND (?2 = '' OR c.status = ?2)
    AND (?3 = '' OR LOWER(c.plan_type) = LOWER(?3))
    AND (?4 = 0 OR q.synced_at IS NULL OR q.synced_at = '')
ORDER BY c.id
LIMIT ?6 OFFSET ?5
`

type ListCodexPagedParams struct {
	Search       interface{} `json:"search"`
	Status       interface{} `json:"status"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
	PageOffset   int64       `json:"page_offset"`
	PageLimit    int64       `json:"page_limit"`
}

type ListCodexPagedRow struct {
	ID             string  `json:"id"`
	Status         string  `json:"status"`
	AccessToken    string  `json:"access_token"`
	Expired        string  `json:"expired"`
	RefreshToken   string  `json:"refresh_token"`
	PlanType       string  `json:"plan_type"`
	Reason         string  `json:"reason"`
	Quota5h        float64 `json:"quota_5h"`
	Quota7d        float64 `json:"quota_7d"`
	QuotaSpark5h   float64 `json:"quota_spark_5h"`
	QuotaSpark7d   float64 `json:"quota_spark_7d"`
	Reset5h        string  `json:"reset_5h"`
	Reset7d        string  `json:"reset_7d"`
	ResetSpark5h   string  `json:"reset_spark_5h"`
	ResetSpark7d   string  `json:"reset_spark_7d"`
	ThrottledUntil string  `json:"throttled_until"`
	SyncedAt       string  `json:"synced_at"`
}

func (q *Queries) ListCodexPaged(ctx context.Context, arg ListCodexPagedParams) ([]ListCodexPagedRow, error) {
	rows, err := q.db.QueryContext(ctx, listCodexPaged,
		arg.Search,
		arg.Status,
		arg.PlanType,
		arg.UnsyncedOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCodexPagedRow{}
	for rows.Next() {
		var i ListCodexPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.Expired,
			&i.RefreshToken,
			&i.PlanType,
			&i.Reason,
			&i.Quota5h,
			&i.Quota7d,
			&i.QuotaSpark5h,
			&i.QuotaSpark7d,
			&i.Reset5h,
			&i.Reset7d,
			&i.ResetSpark5h,
			&i.ResetSpark7d,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreExpiredThrottledCodex = `-- name: RestoreExpiredThrottledCodex :exec
UPDATE codex
SET status = 'enabled', reason = ''
WHERE status = 'throttled'
  AND id IN (
    SELECT c.id
    FROM codex c
    LEFT JOIN codex_quota q ON q.credential_id = c.id
    WHERE c.status = 'throttled'
      AND COALESCE(q.throttled_until, datetime('now')) <= datetime('now')
      AND COALESCE(q.throttled_until_spark, datetime('now')) <= datetime('now')
  )
`

func (q *Queries) RestoreExpiredThrottledCodex(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, restoreExpiredThrottledCodex)
	return err
}

const updateCodexStatus = `-- name: UpdateCodexStatus :one
UPDATE codex SET status = ?, reason = ? WHERE id = ?
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type UpdateCodexStatusParams struct {
	Status string `json:"status"`
	Reason string `json:"reason"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateCodexStatus(ctx context.Context, arg UpdateCodexStatusParams) (Codex, error) {
	row := q.db.QueryRowContext(ctx, updateCodexStatus, arg.Status, arg.Reason, arg.ID)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const updateCodexTokens = `-- name: UpdateCodexTokens :one
UPDATE codex
SET
    status = ?,
    access_token = ?,
    expired = ?,
    refresh_token = ?,
    plan_type = ?,
    reason = ''
WHERE id = ?
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type UpdateCodexTokensParams struct {
	Status       string `json:"status"`
	AccessToken  string `json:"access_token"`
	Expired      string `json:"expired"`
	RefreshToken string `json:"refresh_token"`
	PlanType     string `json:"plan_type"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateCodexTokens(ctx context.Context, arg UpdateCodexTokensParams) (Codex, error) {
	row := q.db.QueryRowContext(ctx, updateCodexTokens,
		arg.Status,
		arg.AccessToken,
		arg.Expired,
		arg.RefreshToken,
		arg.PlanType,
		arg.ID,
	)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}
