// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: codex.sql

package sqlite

import (
	"context"
)

const countCodex = `-- name: CountCodex :one
SELECT COUNT(*) FROM codex
`

func (q *Queries) CountCodex(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCodex)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCodexFiltered = `-- name: CountCodexFiltered :one
SELECT COUNT(*)
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
WHERE
    (?1 = '' OR LOWER(c.id) LIKE ?1 OR LOWER(c.status) LIKE ?1 OR LOWER(c.plan_type) LIKE ?1)
    AND (
        ?2 = ''
        OR (
            (instr(',' || ?2 || ',', ',enabled,') = 0 OR c.status = 'enabled')
            AND (instr(',' || ?2 || ',', ',disabled,') = 0 OR c.status = 'disabled')
            AND (instr(',' || ?2 || ',', ',throttled:all,') = 0 OR q.throttled_until > datetime('now') OR q.throttled_until_spark > datetime('now'))
            AND (instr(',' || ?2 || ',', ',throttled:default,') = 0 OR q.throttled_until > datetime('now'))
            AND (instr(',' || ?2 || ',', ',throttled:spark,') = 0 OR q.throttled_until_spark > datetime('now'))
        )
    )
    AND (?3 = '' OR LOWER(c.plan_type) = LOWER(?3))
    AND (?4 = 0 OR q.synced_at IS NULL OR q.synced_at = '')
`

type CountCodexFilteredParams struct {
	Search       interface{} `json:"search"`
	Statuses     interface{} `json:"statuses"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
}

func (q *Queries) CountCodexFiltered(ctx context.Context, arg CountCodexFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCodexFiltered,
		arg.Search,
		arg.Statuses,
		arg.PlanType,
		arg.UnsyncedOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledCodex = `-- name: CountEnabledCodex :one
SELECT COUNT(*)
FROM codex
WHERE status = 'enabled'
`

func (q *Queries) CountEnabledCodex(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledCodex)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCodex = `-- name: CreateCodex :one
INSERT INTO codex (id, status, access_token, expired, refresh_token, plan_type)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type CreateCodexParams struct {
	ID           string `json:"id"`
	Status       string `json:"status"`
	AccessToken  string `json:"access_token"`
	Expired      string `json:"expired"`
	RefreshToken string `json:"refresh_token"`
	PlanType     string `json:"plan_type"`
}

func (q *Queries) CreateCodex(ctx context.Context, arg CreateCodexParams) (Codex, error) {
	row := q.db.QueryRowContext(ctx, createCodex,
		arg.ID,
		arg.Status,
		arg.AccessToken,
		arg.Expired,
		arg.RefreshToken,
		arg.PlanType,
	)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const deleteCodex = `-- name: DeleteCodex :execrows
DELETE FROM codex WHERE id = ?
`

func (q *Queries) DeleteCodex(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCodex, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCodex = `-- name: GetCodex :one
SELECT id, status, access_token, expired, refresh_token, plan_type, reason
FROM codex
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCodex(ctx context.Context, id string) (Codex, error) {
	row := q.db.QueryRowContext(ctx, getCodex, id)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const listCodex = `-- name: ListCodex :many
SELECT
    c.id, c.status, c.access_token, c.expired, c.refresh_token, c.plan_type, c.reason,
    COALESCE(q.quota_5h, 1.0) AS quota_5h,
    COALESCE(q.quota_7d, 1.0) AS quota_7d,
    COALESCE(q.quota_1mo, 1.0) AS quota_1mo,
    COALESCE(q.quota_spark_5h, 1.0) AS quota_spark_5h,
    COALESCE(q.quota_spark_7d, 1.0) AS quota_spark_7d,
    COALESCE(q.quota_spark_1mo, 1.0) AS quota_spark_1mo,
    COALESCE(q.reset_5h, '') AS reset_5h,
    COALESCE(q.reset_7d, '') AS reset_7d,
    COALESCE(q.reset_1mo, '') AS reset_1mo,
    COALESCE(q.reset_spark_5h, '') AS reset_spark_5h,
    COALESCE(q.reset_spark_7d, '') AS reset_spark_7d,
    COALESCE(q.reset_spark_1mo, '') AS reset_spark_1mo,
    COALESCE(q.throttled_until, '') AS throttled_until_default,
    COALESCE(q.throttled_until_spark, '') AS throttled_until_spark,
    COALESCE(q.synced_at, '') AS synced_at
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
ORDER BY c.id
`

type ListCodexRow struct {
	ID                    string  `json:"id"`
	Status                string  `json:"status"`
	AccessToken           string  `json:"access_token"`
	Expired               string  `json:"expired"`
	RefreshToken          string  `json:"refresh_token"`
	PlanType              string  `json:"plan_type"`
	Reason                string  `json:"reason"`
	Quota5h               float64 `json:"quota_5h"`
	Quota7d               float64 `json:"quota_7d"`
	Quota1mo              float64 `json:"quota_1mo"`
	QuotaSpark5h          float64 `json:"quota_spark_5h"`
	QuotaSpark7d          float64 `json:"quota_spark_7d"`
	QuotaSpark1mo         float64 `json:"quota_spark_1mo"`
	Reset5h               string  `json:"reset_5h"`
	Reset7d               string  `json:"reset_7d"`
	Reset1mo              string  `json:"reset_1mo"`
	ResetSpark5h          string  `json:"reset_spark_5h"`
	ResetSpark7d          string  `json:"reset_spark_7d"`
	ResetSpark1mo         string  `json:"reset_spark_1mo"`
	ThrottledUntilDefault string  `json:"throttled_until_default"`
	ThrottledUntilSpark   string  `json:"throttled_until_spark"`
	SyncedAt              string  `json:"synced_at"`
}

func (q *Queries) ListCodex(ctx context.Context) ([]ListCodexRow, error) {
	rows, err := q.db.QueryContext(ctx, listCodex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCodexRow{}
	for rows.Next() {
		var i ListCodexRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.Expired,
			&i.RefreshToken,
			&i.PlanType,
			&i.Reason,
			&i.Quota5h,
			&i.Quota7d,
			&i.Quota1mo,
			&i.QuotaSpark5h,
			&i.QuotaSpark7d,
			&i.QuotaSpark1mo,
			&i.Reset5h,
			&i.Reset7d,
			&i.Reset1mo,
			&i.ResetSpark5h,
			&i.ResetSpark7d,
			&i.ResetSpark1mo,
			&i.ThrottledUntilDefault,
			&i.ThrottledUntilSpark,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodexPaged = `-- name: ListCodexPaged :many
SELECT
    c.id, c.status, c.access_token, c.expired, c.refresh_token, c.plan_type, c.reason,
    COALESCE(q.quota_5h, 1.0) AS quota_5h,
    COALESCE(q.quota_7d, 1.0) AS quota_7d,
    COALESCE(q.quota_1mo, 1.0) AS quota_1mo,
    COALESCE(q.quota_spark_5h, 1.0) AS quota_spark_5h,
    COALESCE(q.quota_spark_7d, 1.0) AS quota_spark_7d,
    COALESCE(q.quota_spark_1mo, 1.0) AS quota_spark_1mo,
    COALESCE(q.reset_5h, '') AS reset_5h,
    COALESCE(q.reset_7d, '') AS reset_7d,
    COALESCE(q.reset_1mo, '') AS reset_1mo,
    COALESCE(q.reset_spark_5h, '') AS reset_spark_5h,
    COALESCE(q.reset_spark_7d, '') AS reset_spark_7d,
    COALESCE(q.reset_spark_1mo, '') AS reset_spark_1mo,
    COALESCE(q.throttled_until, '') AS throttled_until_default,
    COALESCE(q.throttled_until_spark, '') AS throttled_until_spark,
    COALESCE(q.synced_at, '') AS synced_at
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
WHERE
    (?1 = '' OR LOWER(c.id) LIKE ?1 OR LOWER(c.status) LIKE ?1 OR LOWER(c.plan_type) LIKE ?1)
    AND (
        ?2 = ''
        OR (
            (instr(',' || ?2 || ',', ',enabled,') = 0 OR c.status = 'enabled')
            AND (instr(',' || ?2 || ',', ',disabled,') = 0 OR c.status = 'disabled')
            AND (instr(',' || ?2 || ',', ',throttled:all,') = 0 OR q.throttled_until > datetime('now') OR q.throttled_until_spark > datetime('now'))
            AND (instr(',' || ?2 || ',', ',throttled:default,') = 0 OR q.throttled_until > datetime('now'))
            AND (instr(',' || ?2 || ',', ',throttled:spark,') = 0 OR q.throttled_until_spark > datetime('now'))
        )
    )
    AND (?3 = '' OR LOWER(c.plan_type) = LOWER(?3))
    AND (?4 = 0 OR q.synced_at IS NULL OR q.synced_at = '')
ORDER BY c.id
LIMIT ?6 OFFSET ?5
`

type ListCodexPagedParams struct {
	Search       interface{} `json:"search"`
	Statuses     interface{} `json:"statuses"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
	PageOffset   int64       `json:"page_offset"`
	PageLimit    int64       `json:"page_limit"`
}

type ListCodexPagedRow struct {
	ID                    string  `json:"id"`
	Status                string  `json:"status"`
	AccessToken           string  `json:"access_token"`
	Expired               string  `json:"expired"`
	RefreshToken          string  `json:"refresh_token"`
	PlanType              string  `json:"plan_type"`
	Reason                string  `json:"reason"`
	Quota5h               float64 `json:"quota_5h"`
	Quota7d               float64 `json:"quota_7d"`
	Quota1mo              float64 `json:"quota_1mo"`
	QuotaSpark5h          float64 `json:"quota_spark_5h"`
	QuotaSpark7d          float64 `json:"quota_spark_7d"`
	QuotaSpark1mo         float64 `json:"quota_spark_1mo"`
	Reset5h               string  `json:"reset_5h"`
	Reset7d               string  `json:"reset_7d"`
	Reset1mo              string  `json:"reset_1mo"`
	ResetSpark5h          string  `json:"reset_spark_5h"`
	ResetSpark7d          string  `json:"reset_spark_7d"`
	ResetSpark1mo         string  `json:"reset_spark_1mo"`
	ThrottledUntilDefault string  `json:"throttled_until_default"`
	ThrottledUntilSpark   string  `json:"throttled_until_spark"`
	SyncedAt              string  `json:"synced_at"`
}

func (q *Queries) ListCodexPaged(ctx context.Context, arg ListCodexPagedParams) ([]ListCodexPagedRow, error) {
	rows, err := q.db.QueryContext(ctx, listCodexPaged,
		arg.Search,
		arg.Statuses,
		arg.PlanType,
		arg.UnsyncedOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCodexPagedRow{}
	for rows.Next() {
		var i ListCodexPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.Expired,
			&i.RefreshToken,
			&i.PlanType,
			&i.Reason,
			&i.Quota5h,
			&i.Quota7d,
			&i.Quota1mo,
			&i.QuotaSpark5h,
			&i.QuotaSpark7d,
			&i.QuotaSpark1mo,
			&i.Reset5h,
			&i.Reset7d,
			&i.Reset1mo,
			&i.ResetSpark5h,
			&i.ResetSpark7d,
			&i.ResetSpark1mo,
			&i.ThrottledUntilDefault,
			&i.ThrottledUntilSpark,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodexPlanTypes = `-- name: ListCodexPlanTypes :many
SELECT DISTINCT LOWER(TRIM(c.plan_type)) AS plan_type
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
WHERE
    (?1 = '' OR LOWER(c.id) LIKE ?1 OR LOWER(c.status) LIKE ?1 OR LOWER(c.plan_type) LIKE ?1)
    AND (
        ?2 = ''
        OR (
            (instr(',' || ?2 || ',', ',enabled,') = 0 OR c.status = 'enabled')
            AND (instr(',' || ?2 || ',', ',disabled,') = 0 OR c.status = 'disabled')
            AND (instr(',' || ?2 || ',', ',throttled:all,') = 0 OR q.throttled_until > datetime('now') OR q.throttled_until_spark > datetime('now'))
            AND (instr(',' || ?2 || ',', ',throttled:default,') = 0 OR q.throttled_until > datetime('now'))
            AND (instr(',' || ?2 || ',', ',throttled:spark,') = 0 OR q.throttled_until_spark > datetime('now'))
        )
    )
    AND (?3 = 0 OR q.synced_at IS NULL OR q.synced_at = '')
    AND TRIM(c.plan_type) <> ''
ORDER BY plan_type
`

type ListCodexPlanTypesParams struct {
	Search       interface{} `json:"search"`
	Statuses     interface{} `json:"statuses"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
}

func (q *Queries) ListCodexPlanTypes(ctx context.Context, arg ListCodexPlanTypesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCodexPlanTypes, arg.Search, arg.Statuses, arg.UnsyncedOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var plan_type string
		if err := rows.Scan(&plan_type); err != nil {
			return nil, err
		}
		items = append(items, plan_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCodexThrottleDeadline = `-- name: NextCodexThrottleDeadline :one
SELECT CAST(COALESCE(MIN(deadline), '') AS TEXT) AS deadline
FROM (
    SELECT q.throttled_until AS deadline
    FROM codex c
    JOIN codex_quota q ON q.credential_id = c.id
    WHERE c.status <> 'disabled' AND q.throttled_until > datetime('now')
    UNION ALL
    SELECT q.throttled_until_spark AS deadline
    FROM codex c
    JOIN codex_quota q ON q.credential_id = c.id
    WHERE c.status <> 'disabled' AND q.throttled_until_spark > datetime('now')
)
`

func (q *Queries) NextCodexThrottleDeadline(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, nextCodexThrottleDeadline)
	var deadline string
	err := row.Scan(&deadline)
	return deadline, err
}

const restoreExpiredThrottledCodex = `-- name: RestoreExpiredThrottledCodex :exec
UPDATE codex
SET status = 'enabled', reason = ''
WHERE status = 'throttled'
`

func (q *Queries) RestoreExpiredThrottledCodex(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, restoreExpiredThrottledCodex)
	return err
}

const updateCodexPlanType = `-- name: UpdateCodexPlanType :one
UPDATE codex
SET
    plan_type = ?,
    reason = ''
WHERE id = ?
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type UpdateCodexPlanTypeParams struct {
	PlanType string `json:"plan_type"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateCodexPlanType(ctx context.Context, arg UpdateCodexPlanTypeParams) (Codex, error) {
	row := q.db.QueryRowContext(ctx, updateCodexPlanType, arg.PlanType, arg.ID)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const updateCodexStatus = `-- name: UpdateCodexStatus :one
UPDATE codex SET status = ?, reason = ? WHERE id = ?
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type UpdateCodexStatusParams struct {
	Status string `json:"status"`
	Reason string `json:"reason"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateCodexStatus(ctx context.Context, arg UpdateCodexStatusParams) (Codex, error) {
	row := q.db.QueryRowContext(ctx, updateCodexStatus, arg.Status, arg.Reason, arg.ID)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const updateCodexTokens = `-- name: UpdateCodexTokens :one
UPDATE codex
SET
    status = ?,
    access_token = ?,
    expired = ?,
    refresh_token = ?,
    plan_type = ?,
    reason = ''
WHERE id = ?
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type UpdateCodexTokensParams struct {
	Status       string `json:"status"`
	AccessToken  string `json:"access_token"`
	Expired      string `json:"expired"`
	RefreshToken string `json:"refresh_token"`
	PlanType     string `json:"plan_type"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateCodexTokens(ctx context.Context, arg UpdateCodexTokensParams) (Codex, error) {
	row := q.db.QueryRowContext(ctx, updateCodexTokens,
		arg.Status,
		arg.AccessToken,
		arg.Expired,
		arg.RefreshToken,
		arg.PlanType,
		arg.ID,
	)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}
