// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gemini_quota.sql

package sqlite

import (
	"context"
)

const deleteGeminiQuota = `-- name: DeleteGeminiQuota :execrows
DELETE FROM gemini_quota WHERE credential_id = ?
`

// Deletes the gemini_quota record for a credential.
func (q *Queries) DeleteGeminiQuota(ctx context.Context, credentialID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGeminiQuota, credentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGeminiQuota = `-- name: GetGeminiQuota :one
SELECT credential_id, quota_pro, reset_pro, quota_flash, reset_flash, quota_flashlite, reset_flashlite, throttled_until_pro, throttled_until_flash, throttled_until_flashlite, synced_at FROM gemini_quota WHERE credential_id = ? LIMIT 1
`

func (q *Queries) GetGeminiQuota(ctx context.Context, credentialID string) (GeminiQuotum, error) {
	row := q.db.QueryRowContext(ctx, getGeminiQuota, credentialID)
	var i GeminiQuotum
	err := row.Scan(
		&i.CredentialID,
		&i.QuotaPro,
		&i.ResetPro,
		&i.QuotaFlash,
		&i.ResetFlash,
		&i.QuotaFlashlite,
		&i.ResetFlashlite,
		&i.ThrottledUntilPro,
		&i.ThrottledUntilFlash,
		&i.ThrottledUntilFlashlite,
		&i.SyncedAt,
	)
	return i, err
}

const listAvailableGeminiCLI = `-- name: ListAvailableGeminiCLI :many
SELECT
    g.id,
    g.email,
    g.project_id,
    g.plan_type,
    COALESCE(q.quota_pro, 1.0)                        AS quota_pro,
    COALESCE(q.reset_pro, datetime('now'))             AS reset_pro,
    COALESCE(q.quota_flash, 1.0)                       AS quota_flash,
    COALESCE(q.reset_flash, datetime('now'))           AS reset_flash,
    COALESCE(q.quota_flashlite, 1.0)                   AS quota_flashlite,
    COALESCE(q.reset_flashlite, datetime('now'))       AS reset_flashlite,
    COALESCE(q.throttled_until_pro, datetime('now'))       AS throttled_until_pro,
    COALESCE(q.throttled_until_flash, datetime('now'))     AS throttled_until_flash,
    COALESCE(q.throttled_until_flashlite, datetime('now')) AS throttled_until_flashlite,
    CAST(max(COALESCE(q.throttled_until_pro, datetime('now')), COALESCE(q.throttled_until_flash, datetime('now')), COALESCE(q.throttled_until_flashlite, datetime('now'))) AS TEXT) AS throttled_until,
    COALESCE(q.synced_at, '')                          AS synced_at
FROM gemini g
LEFT JOIN gemini_quota q ON q.credential_id = g.id
WHERE g.status = 'enabled'
  AND (g.expired > datetime('now') OR g.refresh_token != '')
ORDER BY
    COALESCE(q.quota_pro, 1.0) DESC,
    COALESCE(q.quota_flash, 1.0) DESC,
    COALESCE(q.quota_flashlite, 1.0) DESC
`

type ListAvailableGeminiCLIRow struct {
	ID                      string  `json:"id"`
	Email                   string  `json:"email"`
	ProjectID               string  `json:"project_id"`
	PlanType                string  `json:"plan_type"`
	QuotaPro                float64 `json:"quota_pro"`
	ResetPro                string  `json:"reset_pro"`
	QuotaFlash              float64 `json:"quota_flash"`
	ResetFlash              string  `json:"reset_flash"`
	QuotaFlashlite          float64 `json:"quota_flashlite"`
	ResetFlashlite          string  `json:"reset_flashlite"`
	ThrottledUntilPro       string  `json:"throttled_until_pro"`
	ThrottledUntilFlash     string  `json:"throttled_until_flash"`
	ThrottledUntilFlashlite string  `json:"throttled_until_flashlite"`
	ThrottledUntil          string  `json:"throttled_until"`
	SyncedAt                string  `json:"synced_at"`
}

// Returns enabled, non-throttled Gemini credentials with quota info
func (q *Queries) ListAvailableGeminiCLI(ctx context.Context) ([]ListAvailableGeminiCLIRow, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableGeminiCLI)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableGeminiCLIRow{}
	for rows.Next() {
		var i ListAvailableGeminiCLIRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ProjectID,
			&i.PlanType,
			&i.QuotaPro,
			&i.ResetPro,
			&i.QuotaFlash,
			&i.ResetFlash,
			&i.QuotaFlashlite,
			&i.ResetFlashlite,
			&i.ThrottledUntilPro,
			&i.ThrottledUntilFlash,
			&i.ThrottledUntilFlashlite,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGeminiQuotaThrottledAll = `-- name: SetGeminiQuotaThrottledAll :exec
INSERT INTO gemini_quota (credential_id, throttled_until_pro, throttled_until_flash, throttled_until_flashlite, synced_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_pro = excluded.throttled_until_pro,
    throttled_until_flash = excluded.throttled_until_flash,
    throttled_until_flashlite = excluded.throttled_until_flashlite,
    synced_at = datetime('now')
`

type SetGeminiQuotaThrottledAllParams struct {
	CredentialID            string `json:"credential_id"`
	ThrottledUntilPro       string `json:"throttled_until_pro"`
	ThrottledUntilFlash     string `json:"throttled_until_flash"`
	ThrottledUntilFlashlite string `json:"throttled_until_flashlite"`
}

// Sets all tier throttles for a Gemini credential.
func (q *Queries) SetGeminiQuotaThrottledAll(ctx context.Context, arg SetGeminiQuotaThrottledAllParams) error {
	_, err := q.db.ExecContext(ctx, setGeminiQuotaThrottledAll,
		arg.CredentialID,
		arg.ThrottledUntilPro,
		arg.ThrottledUntilFlash,
		arg.ThrottledUntilFlashlite,
	)
	return err
}

const setGeminiQuotaThrottledFlash = `-- name: SetGeminiQuotaThrottledFlash :exec
INSERT INTO gemini_quota (credential_id, throttled_until_flash, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_flash = excluded.throttled_until_flash,
    synced_at = datetime('now')
`

type SetGeminiQuotaThrottledFlashParams struct {
	CredentialID        string `json:"credential_id"`
	ThrottledUntilFlash string `json:"throttled_until_flash"`
}

// Sets the Flash tier throttle for a Gemini credential.
func (q *Queries) SetGeminiQuotaThrottledFlash(ctx context.Context, arg SetGeminiQuotaThrottledFlashParams) error {
	_, err := q.db.ExecContext(ctx, setGeminiQuotaThrottledFlash, arg.CredentialID, arg.ThrottledUntilFlash)
	return err
}

const setGeminiQuotaThrottledFlashLite = `-- name: SetGeminiQuotaThrottledFlashLite :exec
INSERT INTO gemini_quota (credential_id, throttled_until_flashlite, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_flashlite = excluded.throttled_until_flashlite,
    synced_at = datetime('now')
`

type SetGeminiQuotaThrottledFlashLiteParams struct {
	CredentialID            string `json:"credential_id"`
	ThrottledUntilFlashlite string `json:"throttled_until_flashlite"`
}

// Sets the Flash Lite tier throttle for a Gemini credential.
func (q *Queries) SetGeminiQuotaThrottledFlashLite(ctx context.Context, arg SetGeminiQuotaThrottledFlashLiteParams) error {
	_, err := q.db.ExecContext(ctx, setGeminiQuotaThrottledFlashLite, arg.CredentialID, arg.ThrottledUntilFlashlite)
	return err
}

const setGeminiQuotaThrottledPro = `-- name: SetGeminiQuotaThrottledPro :exec
INSERT INTO gemini_quota (credential_id, throttled_until_pro, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_pro = excluded.throttled_until_pro,
    synced_at = datetime('now')
`

type SetGeminiQuotaThrottledProParams struct {
	CredentialID      string `json:"credential_id"`
	ThrottledUntilPro string `json:"throttled_until_pro"`
}

// Sets the Pro tier throttle for a Gemini credential.
func (q *Queries) SetGeminiQuotaThrottledPro(ctx context.Context, arg SetGeminiQuotaThrottledProParams) error {
	_, err := q.db.ExecContext(ctx, setGeminiQuotaThrottledPro, arg.CredentialID, arg.ThrottledUntilPro)
	return err
}

const upsertGeminiQuota = `-- name: UpsertGeminiQuota :one
INSERT INTO gemini_quota (credential_id, quota_pro, reset_pro, quota_flash, reset_flash, quota_flashlite, reset_flashlite, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    quota_pro = excluded.quota_pro,
    reset_pro = excluded.reset_pro,
    quota_flash = excluded.quota_flash,
    reset_flash = excluded.reset_flash,
    quota_flashlite = excluded.quota_flashlite,
    reset_flashlite = excluded.reset_flashlite,
    synced_at = datetime('now')
RETURNING credential_id, quota_pro, reset_pro, quota_flash, reset_flash, quota_flashlite, reset_flashlite, throttled_until_pro, throttled_until_flash, throttled_until_flashlite, synced_at
`

type UpsertGeminiQuotaParams struct {
	CredentialID   string  `json:"credential_id"`
	QuotaPro       float64 `json:"quota_pro"`
	ResetPro       string  `json:"reset_pro"`
	QuotaFlash     float64 `json:"quota_flash"`
	ResetFlash     string  `json:"reset_flash"`
	QuotaFlashlite float64 `json:"quota_flashlite"`
	ResetFlashlite string  `json:"reset_flashlite"`
}

// Syncs per-tier quota ratios and reset timestamps for Gemini credentials.
func (q *Queries) UpsertGeminiQuota(ctx context.Context, arg UpsertGeminiQuotaParams) (GeminiQuotum, error) {
	row := q.db.QueryRowContext(ctx, upsertGeminiQuota,
		arg.CredentialID,
		arg.QuotaPro,
		arg.ResetPro,
		arg.QuotaFlash,
		arg.ResetFlash,
		arg.QuotaFlashlite,
		arg.ResetFlashlite,
	)
	var i GeminiQuotum
	err := row.Scan(
		&i.CredentialID,
		&i.QuotaPro,
		&i.ResetPro,
		&i.QuotaFlash,
		&i.ResetFlash,
		&i.QuotaFlashlite,
		&i.ResetFlashlite,
		&i.ThrottledUntilPro,
		&i.ThrottledUntilFlash,
		&i.ThrottledUntilFlashlite,
		&i.SyncedAt,
	)
	return i, err
}
