// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
)

type Antigravity struct {
	ID           string `json:"id"`
	Status       string `json:"status"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	Expired      string `json:"expired"`
	Email        string `json:"email"`
	ProjectID    string `json:"project_id"`
	PlanType     string `json:"plan_type"`
	Reason       string `json:"reason"`
	SyncedAt     string `json:"synced_at"`
}

type AntigravityCredit struct {
	CredentialID  string  `json:"credential_id"`
	CreditsAmount float64 `json:"credits_amount"`
	CreditTypes   string  `json:"credit_types"`
	SyncedAt      string  `json:"synced_at"`
}

type AntigravityQuotum struct {
	CredentialID            string  `json:"credential_id"`
	QuotaClaude             float64 `json:"quota_claude"`
	ResetClaude             string  `json:"reset_claude"`
	QuotaPro                float64 `json:"quota_pro"`
	ResetPro                string  `json:"reset_pro"`
	QuotaFlash              float64 `json:"quota_flash"`
	ResetFlash              string  `json:"reset_flash"`
	QuotaFlashlite          float64 `json:"quota_flashlite"`
	ResetFlashlite          string  `json:"reset_flashlite"`
	QuotaTab                float64 `json:"quota_tab"`
	ResetTab                string  `json:"reset_tab"`
	QuotaImage              float64 `json:"quota_image"`
	ResetImage              string  `json:"reset_image"`
	ThrottledUntilClaude    string  `json:"throttled_until_claude"`
	ThrottledUntilPro       string  `json:"throttled_until_pro"`
	ThrottledUntilFlash     string  `json:"throttled_until_flash"`
	ThrottledUntilFlashlite string  `json:"throttled_until_flashlite"`
	ThrottledUntilTab       string  `json:"throttled_until_tab"`
	ThrottledUntilImage     string  `json:"throttled_until_image"`
	SyncedAt                string  `json:"synced_at"`
}

type AuthKey struct {
	Key       string `json:"key"`
	Role      string `json:"role"`
	Note      string `json:"note"`
	CreatedAt string `json:"created_at"`
}

type Codex struct {
	ID           string `json:"id"`
	Status       string `json:"status"`
	AccessToken  string `json:"access_token"`
	Expired      string `json:"expired"`
	RefreshToken string `json:"refresh_token"`
	PlanType     string `json:"plan_type"`
	Reason       string `json:"reason"`
}

type CodexQuotum struct {
	CredentialID        string         `json:"credential_id"`
	Quota5h             float64        `json:"quota_5h"`
	Quota7d             float64        `json:"quota_7d"`
	Quota1mo            float64        `json:"quota_1mo"`
	QuotaSpark5h        float64        `json:"quota_spark_5h"`
	QuotaSpark7d        float64        `json:"quota_spark_7d"`
	QuotaSpark1mo       float64        `json:"quota_spark_1mo"`
	Reset5h             sql.NullString `json:"reset_5h"`
	Reset7d             sql.NullString `json:"reset_7d"`
	Reset1mo            sql.NullString `json:"reset_1mo"`
	ResetSpark5h        sql.NullString `json:"reset_spark_5h"`
	ResetSpark7d        sql.NullString `json:"reset_spark_7d"`
	ResetSpark1mo       sql.NullString `json:"reset_spark_1mo"`
	ResetCreditsCount   int64          `json:"reset_credits_count"`
	ThrottledUntil      string         `json:"throttled_until"`
	ThrottledUntilSpark string         `json:"throttled_until_spark"`
	SyncedAt            string         `json:"synced_at"`
}

type Gemini struct {
	ID           string `json:"id"`
	Status       string `json:"status"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	Expired      string `json:"expired"`
	Email        string `json:"email"`
	ProjectID    string `json:"project_id"`
	PlanType     string `json:"plan_type"`
	Reason       string `json:"reason"`
	SyncedAt     string `json:"synced_at"`
}

type GeminiQuotum struct {
	CredentialID            string  `json:"credential_id"`
	QuotaPro                float64 `json:"quota_pro"`
	ResetPro                string  `json:"reset_pro"`
	QuotaFlash              float64 `json:"quota_flash"`
	ResetFlash              string  `json:"reset_flash"`
	QuotaFlashlite          float64 `json:"quota_flashlite"`
	ResetFlashlite          string  `json:"reset_flashlite"`
	ThrottledUntilPro       string  `json:"throttled_until_pro"`
	ThrottledUntilFlash     string  `json:"throttled_until_flash"`
	ThrottledUntilFlashlite string  `json:"throttled_until_flashlite"`
	SyncedAt                string  `json:"synced_at"`
}

type Model struct {
	Alias     string `json:"alias"`
	Origin    string `json:"origin"`
	Handler   string `json:"handler"`
	PlanTypes string `json:"plan_types"`
	Plugin    string `json:"plugin"`
	Extra     string `json:"extra"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}
