// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: models.sql

package sqlite

import (
	"context"
)

const countModels = `-- name: CountModels :one
SELECT COUNT(*) FROM models
`

func (q *Queries) CountModels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModelsByHandler = `-- name: CountModelsByHandler :one
SELECT COUNT(*) FROM models WHERE handler = ?
`

func (q *Queries) CountModelsByHandler(ctx context.Context, handler string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModelsByHandler, handler)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModel = `-- name: CreateModel :one
INSERT INTO models (alias, origin, handler, plan_types, extra)
VALUES (?, ?, ?, ?, ?)
RETURNING alias, origin, handler, plan_types, extra
`

type CreateModelParams struct {
	Alias     string `json:"alias"`
	Origin    string `json:"origin"`
	Handler   string `json:"handler"`
	PlanTypes string `json:"plan_types"`
	Extra     string `json:"extra"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRowContext(ctx, createModel,
		arg.Alias,
		arg.Origin,
		arg.Handler,
		arg.PlanTypes,
		arg.Extra,
	)
	var i Model
	err := row.Scan(
		&i.Alias,
		&i.Origin,
		&i.Handler,
		&i.PlanTypes,
		&i.Extra,
	)
	return i, err
}

const deleteModel = `-- name: DeleteModel :execrows
DELETE FROM models WHERE alias = ?
`

func (q *Queries) DeleteModel(ctx context.Context, alias string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteModel, alias)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listModels = `-- name: ListModels :many
SELECT alias, origin, handler, plan_types, extra FROM models ORDER BY alias
`

func (q *Queries) ListModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.Alias,
			&i.Origin,
			&i.Handler,
			&i.PlanTypes,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reverseInfoFromModel = `-- name: ReverseInfoFromModel :one
SELECT origin, handler, plan_types, extra
FROM models
WHERE alias = ?
LIMIT 1
`

type ReverseInfoFromModelRow struct {
	Origin    string `json:"origin"`
	Handler   string `json:"handler"`
	PlanTypes string `json:"plan_types"`
	Extra     string `json:"extra"`
}

func (q *Queries) ReverseInfoFromModel(ctx context.Context, alias string) (ReverseInfoFromModelRow, error) {
	row := q.db.QueryRowContext(ctx, reverseInfoFromModel, alias)
	var i ReverseInfoFromModelRow
	err := row.Scan(
		&i.Origin,
		&i.Handler,
		&i.PlanTypes,
		&i.Extra,
	)
	return i, err
}

const updateModel = `-- name: UpdateModel :one
UPDATE models
SET origin = ?, handler = ?, plan_types = ?, extra = ?
WHERE alias = ?
RETURNING alias, origin, handler, plan_types, extra
`

type UpdateModelParams struct {
	Origin    string `json:"origin"`
	Handler   string `json:"handler"`
	PlanTypes string `json:"plan_types"`
	Extra     string `json:"extra"`
	Alias     string `json:"alias"`
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRowContext(ctx, updateModel,
		arg.Origin,
		arg.Handler,
		arg.PlanTypes,
		arg.Extra,
		arg.Alias,
	)
	var i Model
	err := row.Scan(
		&i.Alias,
		&i.Origin,
		&i.Handler,
		&i.PlanTypes,
		&i.Extra,
	)
	return i, err
}
