// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package sqlite

import (
	"context"
	"database/sql"
)

const deleteQuota = `-- name: DeleteQuota :execrows
DELETE FROM codex_quota WHERE credential_id = ?
`

// Deletes the quota record for a credential.
func (q *Queries) DeleteQuota(ctx context.Context, credentialID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteQuota, credentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getQuota = `-- name: GetQuota :one
SELECT credential_id, quota_5h, quota_7d, quota_spark_5h, quota_spark_7d, reset_5h, reset_7d, reset_spark_5h, reset_spark_7d, throttled_until, throttled_until_spark, synced_at FROM codex_quota WHERE credential_id = ? LIMIT 1
`

func (q *Queries) GetQuota(ctx context.Context, credentialID string) (CodexQuotum, error) {
	row := q.db.QueryRowContext(ctx, getQuota, credentialID)
	var i CodexQuotum
	err := row.Scan(
		&i.CredentialID,
		&i.Quota5h,
		&i.Quota7d,
		&i.QuotaSpark5h,
		&i.QuotaSpark7d,
		&i.Reset5h,
		&i.Reset7d,
		&i.ResetSpark5h,
		&i.ResetSpark7d,
		&i.ThrottledUntil,
		&i.ThrottledUntilSpark,
		&i.SyncedAt,
	)
	return i, err
}

const listAvailableCodex = `-- name: ListAvailableCodex :many
SELECT
    c.id,
    c.plan_type,
    COALESCE(q.quota_5h, 1.0)                    AS quota_5h,
    COALESCE(q.quota_7d, 1.0)                    AS quota_7d,
    COALESCE(q.quota_spark_5h, 1.0)              AS quota_spark_5h,
    COALESCE(q.quota_spark_7d, 1.0)              AS quota_spark_7d,
    COALESCE(q.reset_5h, '')                      AS reset_5h,
    COALESCE(q.reset_7d, '')                      AS reset_7d,
    COALESCE(q.reset_spark_5h, '')                AS reset_spark_5h,
    COALESCE(q.reset_spark_7d, '')                AS reset_spark_7d,
    COALESCE(q.throttled_until, datetime('now')) AS throttled_until,
    COALESCE(q.throttled_until_spark, datetime('now')) AS throttled_until_spark,
    COALESCE(q.synced_at, '')                     AS synced_at
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
WHERE c.status = 'enabled'
  AND (c.expired > datetime('now') OR c.refresh_token != '')
ORDER BY
    COALESCE(q.quota_5h, 1.0) DESC,
    COALESCE(q.quota_7d, 1.0) DESC
`

type ListAvailableCodexRow struct {
	ID                  string  `json:"id"`
	PlanType            string  `json:"plan_type"`
	Quota5h             float64 `json:"quota_5h"`
	Quota7d             float64 `json:"quota_7d"`
	QuotaSpark5h        float64 `json:"quota_spark_5h"`
	QuotaSpark7d        float64 `json:"quota_spark_7d"`
	Reset5h             string  `json:"reset_5h"`
	Reset7d             string  `json:"reset_7d"`
	ResetSpark5h        string  `json:"reset_spark_5h"`
	ResetSpark7d        string  `json:"reset_spark_7d"`
	ThrottledUntil      string  `json:"throttled_until"`
	ThrottledUntilSpark string  `json:"throttled_until_spark"`
	SyncedAt            string  `json:"synced_at"`
}

// Returns enabled, non-throttled, non-expired credentials
// ordered by highest remaining quota ratio first.
func (q *Queries) ListAvailableCodex(ctx context.Context) ([]ListAvailableCodexRow, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableCodex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableCodexRow{}
	for rows.Next() {
		var i ListAvailableCodexRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanType,
			&i.Quota5h,
			&i.Quota7d,
			&i.QuotaSpark5h,
			&i.QuotaSpark7d,
			&i.Reset5h,
			&i.Reset7d,
			&i.ResetSpark5h,
			&i.ResetSpark7d,
			&i.ThrottledUntil,
			&i.ThrottledUntilSpark,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setQuotaThrottled = `-- name: SetQuotaThrottled :exec
INSERT INTO codex_quota (credential_id, throttled_until, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until = excluded.throttled_until,
    synced_at = datetime('now')
`

type SetQuotaThrottledParams struct {
	CredentialID   string `json:"credential_id"`
	ThrottledUntil string `json:"throttled_until"`
}

// Sets the default tier throttle for a credential.
func (q *Queries) SetQuotaThrottled(ctx context.Context, arg SetQuotaThrottledParams) error {
	_, err := q.db.ExecContext(ctx, setQuotaThrottled, arg.CredentialID, arg.ThrottledUntil)
	return err
}

const setQuotaThrottledAll = `-- name: SetQuotaThrottledAll :exec
INSERT INTO codex_quota (credential_id, throttled_until, throttled_until_spark, synced_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until = excluded.throttled_until,
    throttled_until_spark = excluded.throttled_until_spark,
    synced_at = datetime('now')
`

type SetQuotaThrottledAllParams struct {
	CredentialID        string `json:"credential_id"`
	ThrottledUntil      string `json:"throttled_until"`
	ThrottledUntilSpark string `json:"throttled_until_spark"`
}

// Sets all tier throttles for a credential (non-tier-specific backoff).
func (q *Queries) SetQuotaThrottledAll(ctx context.Context, arg SetQuotaThrottledAllParams) error {
	_, err := q.db.ExecContext(ctx, setQuotaThrottledAll, arg.CredentialID, arg.ThrottledUntil, arg.ThrottledUntilSpark)
	return err
}

const setQuotaThrottledSpark = `-- name: SetQuotaThrottledSpark :exec
INSERT INTO codex_quota (credential_id, throttled_until_spark, synced_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_spark = excluded.throttled_until_spark,
    synced_at = datetime('now')
`

type SetQuotaThrottledSparkParams struct {
	CredentialID        string `json:"credential_id"`
	ThrottledUntilSpark string `json:"throttled_until_spark"`
}

// Sets the spark tier throttle for a credential.
func (q *Queries) SetQuotaThrottledSpark(ctx context.Context, arg SetQuotaThrottledSparkParams) error {
	_, err := q.db.ExecContext(ctx, setQuotaThrottledSpark, arg.CredentialID, arg.ThrottledUntilSpark)
	return err
}

const upsertQuota = `-- name: UpsertQuota :one
INSERT INTO codex_quota (credential_id, quota_5h, quota_7d, quota_spark_5h, quota_spark_7d, reset_5h, reset_7d, reset_spark_5h, reset_spark_7d, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT (credential_id) DO UPDATE
SET
    quota_5h       = EXCLUDED.quota_5h,
    quota_7d       = EXCLUDED.quota_7d,
    quota_spark_5h = EXCLUDED.quota_spark_5h,
    quota_spark_7d = EXCLUDED.quota_spark_7d,
    reset_5h       = EXCLUDED.reset_5h,
    reset_7d       = EXCLUDED.reset_7d,
    reset_spark_5h = EXCLUDED.reset_spark_5h,
    reset_spark_7d = EXCLUDED.reset_spark_7d,
    synced_at      = datetime('now')
RETURNING credential_id, quota_5h, quota_7d, quota_spark_5h, quota_spark_7d, reset_5h, reset_7d, reset_spark_5h, reset_spark_7d, throttled_until, throttled_until_spark, synced_at
`

type UpsertQuotaParams struct {
	CredentialID string         `json:"credential_id"`
	Quota5h      float64        `json:"quota_5h"`
	Quota7d      float64        `json:"quota_7d"`
	QuotaSpark5h float64        `json:"quota_spark_5h"`
	QuotaSpark7d float64        `json:"quota_spark_7d"`
	Reset5h      sql.NullString `json:"reset_5h"`
	Reset7d      sql.NullString `json:"reset_7d"`
	ResetSpark5h sql.NullString `json:"reset_spark_5h"`
	ResetSpark7d sql.NullString `json:"reset_spark_7d"`
}

// Syncs remaining quota ratios and reset timestamps from upstream.
func (q *Queries) UpsertQuota(ctx context.Context, arg UpsertQuotaParams) (CodexQuotum, error) {
	row := q.db.QueryRowContext(ctx, upsertQuota,
		arg.CredentialID,
		arg.Quota5h,
		arg.Quota7d,
		arg.QuotaSpark5h,
		arg.QuotaSpark7d,
		arg.Reset5h,
		arg.Reset7d,
		arg.ResetSpark5h,
		arg.ResetSpark7d,
	)
	var i CodexQuotum
	err := row.Scan(
		&i.CredentialID,
		&i.Quota5h,
		&i.Quota7d,
		&i.QuotaSpark5h,
		&i.QuotaSpark7d,
		&i.Reset5h,
		&i.Reset7d,
		&i.ResetSpark5h,
		&i.ResetSpark7d,
		&i.ThrottledUntil,
		&i.ThrottledUntilSpark,
		&i.SyncedAt,
	)
	return i, err
}
