// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: antigravity_quota.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAntigravityQuotaThrottle = `-- name: ClearAntigravityQuotaThrottle :exec
INSERT INTO antigravity_quota (
    credential_id,
    throttled_until_claude,
    throttled_until_pro,
    throttled_until_flash,
    throttled_until_flashlite,
    throttled_until_tab,
    throttled_until_image,
    synced_at
)
VALUES ($1, NOW(), NOW(), NOW(), NOW(), NOW(), NOW(), NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_claude = NOW(),
    throttled_until_pro = NOW(),
    throttled_until_flash = NOW(),
    throttled_until_flashlite = NOW(),
    throttled_until_tab = NOW(),
    throttled_until_image = NOW(),
    synced_at = NOW()
`

func (q *Queries) ClearAntigravityQuotaThrottle(ctx context.Context, credentialID string) error {
	_, err := q.db.Exec(ctx, clearAntigravityQuotaThrottle, credentialID)
	return err
}

const deleteAntigravityQuota = `-- name: DeleteAntigravityQuota :execrows
DELETE FROM antigravity_quota WHERE credential_id = $1
`

func (q *Queries) DeleteAntigravityQuota(ctx context.Context, credentialID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAntigravityQuota, credentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAvailableAntigravity = `-- name: ListAvailableAntigravity :many
SELECT
    a.id,
    a.email,
    a.project_id,
    a.plan_type,
    COALESCE(q.quota_claude, 1.0) AS quota_claude,
    COALESCE(q.reset_claude, NOW()) AS reset_claude,
    COALESCE(q.quota_pro, 1.0) AS quota_pro,
    COALESCE(q.reset_pro, NOW()) AS reset_pro,
    COALESCE(q.quota_flash, 1.0) AS quota_flash,
    COALESCE(q.reset_flash, NOW()) AS reset_flash,
    COALESCE(q.quota_flashlite, 1.0) AS quota_flashlite,
    COALESCE(q.reset_flashlite, NOW()) AS reset_flashlite,
    COALESCE(q.quota_tab, 1.0) AS quota_tab,
    COALESCE(q.reset_tab, NOW() + INTERVAL '100 years') AS reset_tab,
    COALESCE(q.quota_image, 1.0) AS quota_image,
    COALESCE(q.reset_image, NOW()) AS reset_image,
    COALESCE(c.credits_amount, 0) AS credits_amount,
    COALESCE(c.credit_types, '') AS credit_types,
    COALESCE(q.throttled_until_claude, NOW()) AS throttled_until_claude,
    COALESCE(q.throttled_until_pro, NOW()) AS throttled_until_pro,
    COALESCE(q.throttled_until_flash, NOW()) AS throttled_until_flash,
    COALESCE(q.throttled_until_flashlite, NOW()) AS throttled_until_flashlite,
    COALESCE(q.throttled_until_tab, NOW()) AS throttled_until_tab,
    COALESCE(q.throttled_until_image, NOW()) AS throttled_until_image,
    GREATEST(
        COALESCE(q.throttled_until_claude, NOW()),
        COALESCE(q.throttled_until_pro, NOW()),
        COALESCE(q.throttled_until_flash, NOW()),
        COALESCE(q.throttled_until_flashlite, NOW()),
        COALESCE(q.throttled_until_tab, NOW()),
        COALESCE(q.throttled_until_image, NOW())
    )::timestamptz AS throttled_until,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM antigravity a
LEFT JOIN antigravity_quota q ON q.credential_id = a.id
LEFT JOIN antigravity_credits c ON c.credential_id = a.id
WHERE a.status = 'enabled'
  AND (a.expired > NOW() OR a.refresh_token != '')
ORDER BY
    COALESCE(q.quota_claude, 1.0) DESC,
    COALESCE(q.quota_pro, 1.0) DESC,
    COALESCE(q.quota_flash, 1.0) DESC,
    COALESCE(q.quota_flashlite, 1.0) DESC,
    COALESCE(q.quota_tab, 1.0) DESC,
    COALESCE(q.quota_image, 1.0) DESC
`

type ListAvailableAntigravityRow struct {
	ID                      string             `json:"id"`
	Email                   string             `json:"email"`
	ProjectID               string             `json:"project_id"`
	PlanType                string             `json:"plan_type"`
	QuotaClaude             float64            `json:"quota_claude"`
	ResetClaude             pgtype.Timestamptz `json:"reset_claude"`
	QuotaPro                float64            `json:"quota_pro"`
	ResetPro                pgtype.Timestamptz `json:"reset_pro"`
	QuotaFlash              float64            `json:"quota_flash"`
	ResetFlash              pgtype.Timestamptz `json:"reset_flash"`
	QuotaFlashlite          float64            `json:"quota_flashlite"`
	ResetFlashlite          pgtype.Timestamptz `json:"reset_flashlite"`
	QuotaTab                float64            `json:"quota_tab"`
	ResetTab                pgtype.Timestamptz `json:"reset_tab"`
	QuotaImage              float64            `json:"quota_image"`
	ResetImage              pgtype.Timestamptz `json:"reset_image"`
	CreditsAmount           float64            `json:"credits_amount"`
	CreditTypes             string             `json:"credit_types"`
	ThrottledUntilClaude    pgtype.Timestamptz `json:"throttled_until_claude"`
	ThrottledUntilPro       pgtype.Timestamptz `json:"throttled_until_pro"`
	ThrottledUntilFlash     pgtype.Timestamptz `json:"throttled_until_flash"`
	ThrottledUntilFlashlite pgtype.Timestamptz `json:"throttled_until_flashlite"`
	ThrottledUntilTab       pgtype.Timestamptz `json:"throttled_until_tab"`
	ThrottledUntilImage     pgtype.Timestamptz `json:"throttled_until_image"`
	ThrottledUntil          pgtype.Timestamptz `json:"throttled_until"`
	SyncedAt                pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListAvailableAntigravity(ctx context.Context) ([]ListAvailableAntigravityRow, error) {
	rows, err := q.db.Query(ctx, listAvailableAntigravity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableAntigravityRow{}
	for rows.Next() {
		var i ListAvailableAntigravityRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ProjectID,
			&i.PlanType,
			&i.QuotaClaude,
			&i.ResetClaude,
			&i.QuotaPro,
			&i.ResetPro,
			&i.QuotaFlash,
			&i.ResetFlash,
			&i.QuotaFlashlite,
			&i.ResetFlashlite,
			&i.QuotaTab,
			&i.ResetTab,
			&i.QuotaImage,
			&i.ResetImage,
			&i.CreditsAmount,
			&i.CreditTypes,
			&i.ThrottledUntilClaude,
			&i.ThrottledUntilPro,
			&i.ThrottledUntilFlash,
			&i.ThrottledUntilFlashlite,
			&i.ThrottledUntilTab,
			&i.ThrottledUntilImage,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAntigravityQuotaThrottledAll = `-- name: SetAntigravityQuotaThrottledAll :exec
INSERT INTO antigravity_quota (
    credential_id,
    throttled_until_claude,
    throttled_until_pro,
    throttled_until_flash,
    throttled_until_flashlite,
    throttled_until_tab,
    throttled_until_image,
    synced_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW()
)
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_claude = EXCLUDED.throttled_until_claude,
    throttled_until_pro = EXCLUDED.throttled_until_pro,
    throttled_until_flash = EXCLUDED.throttled_until_flash,
    throttled_until_flashlite = EXCLUDED.throttled_until_flashlite,
    throttled_until_tab = EXCLUDED.throttled_until_tab,
    throttled_until_image = EXCLUDED.throttled_until_image,
    synced_at = NOW()
`

type SetAntigravityQuotaThrottledAllParams struct {
	CredentialID            string             `json:"credential_id"`
	ThrottledUntilClaude    pgtype.Timestamptz `json:"throttled_until_claude"`
	ThrottledUntilPro       pgtype.Timestamptz `json:"throttled_until_pro"`
	ThrottledUntilFlash     pgtype.Timestamptz `json:"throttled_until_flash"`
	ThrottledUntilFlashlite pgtype.Timestamptz `json:"throttled_until_flashlite"`
	ThrottledUntilTab       pgtype.Timestamptz `json:"throttled_until_tab"`
	ThrottledUntilImage     pgtype.Timestamptz `json:"throttled_until_image"`
}

func (q *Queries) SetAntigravityQuotaThrottledAll(ctx context.Context, arg SetAntigravityQuotaThrottledAllParams) error {
	_, err := q.db.Exec(ctx, setAntigravityQuotaThrottledAll,
		arg.CredentialID,
		arg.ThrottledUntilClaude,
		arg.ThrottledUntilPro,
		arg.ThrottledUntilFlash,
		arg.ThrottledUntilFlashlite,
		arg.ThrottledUntilTab,
		arg.ThrottledUntilImage,
	)
	return err
}

const setAntigravityQuotaThrottledClaude = `-- name: SetAntigravityQuotaThrottledClaude :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_claude, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_claude = EXCLUDED.throttled_until_claude,
    synced_at = NOW()
`

type SetAntigravityQuotaThrottledClaudeParams struct {
	CredentialID         string             `json:"credential_id"`
	ThrottledUntilClaude pgtype.Timestamptz `json:"throttled_until_claude"`
}

func (q *Queries) SetAntigravityQuotaThrottledClaude(ctx context.Context, arg SetAntigravityQuotaThrottledClaudeParams) error {
	_, err := q.db.Exec(ctx, setAntigravityQuotaThrottledClaude, arg.CredentialID, arg.ThrottledUntilClaude)
	return err
}

const setAntigravityQuotaThrottledFlash = `-- name: SetAntigravityQuotaThrottledFlash :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_flash, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_flash = EXCLUDED.throttled_until_flash,
    synced_at = NOW()
`

type SetAntigravityQuotaThrottledFlashParams struct {
	CredentialID        string             `json:"credential_id"`
	ThrottledUntilFlash pgtype.Timestamptz `json:"throttled_until_flash"`
}

func (q *Queries) SetAntigravityQuotaThrottledFlash(ctx context.Context, arg SetAntigravityQuotaThrottledFlashParams) error {
	_, err := q.db.Exec(ctx, setAntigravityQuotaThrottledFlash, arg.CredentialID, arg.ThrottledUntilFlash)
	return err
}

const setAntigravityQuotaThrottledFlashLite = `-- name: SetAntigravityQuotaThrottledFlashLite :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_flashlite, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_flashlite = EXCLUDED.throttled_until_flashlite,
    synced_at = NOW()
`

type SetAntigravityQuotaThrottledFlashLiteParams struct {
	CredentialID            string             `json:"credential_id"`
	ThrottledUntilFlashlite pgtype.Timestamptz `json:"throttled_until_flashlite"`
}

func (q *Queries) SetAntigravityQuotaThrottledFlashLite(ctx context.Context, arg SetAntigravityQuotaThrottledFlashLiteParams) error {
	_, err := q.db.Exec(ctx, setAntigravityQuotaThrottledFlashLite, arg.CredentialID, arg.ThrottledUntilFlashlite)
	return err
}

const setAntigravityQuotaThrottledImage = `-- name: SetAntigravityQuotaThrottledImage :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_image, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_image = EXCLUDED.throttled_until_image,
    synced_at = NOW()
`

type SetAntigravityQuotaThrottledImageParams struct {
	CredentialID        string             `json:"credential_id"`
	ThrottledUntilImage pgtype.Timestamptz `json:"throttled_until_image"`
}

func (q *Queries) SetAntigravityQuotaThrottledImage(ctx context.Context, arg SetAntigravityQuotaThrottledImageParams) error {
	_, err := q.db.Exec(ctx, setAntigravityQuotaThrottledImage, arg.CredentialID, arg.ThrottledUntilImage)
	return err
}

const setAntigravityQuotaThrottledPro = `-- name: SetAntigravityQuotaThrottledPro :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_pro, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_pro = EXCLUDED.throttled_until_pro,
    synced_at = NOW()
`

type SetAntigravityQuotaThrottledProParams struct {
	CredentialID      string             `json:"credential_id"`
	ThrottledUntilPro pgtype.Timestamptz `json:"throttled_until_pro"`
}

func (q *Queries) SetAntigravityQuotaThrottledPro(ctx context.Context, arg SetAntigravityQuotaThrottledProParams) error {
	_, err := q.db.Exec(ctx, setAntigravityQuotaThrottledPro, arg.CredentialID, arg.ThrottledUntilPro)
	return err
}

const setAntigravityQuotaThrottledTab = `-- name: SetAntigravityQuotaThrottledTab :exec
INSERT INTO antigravity_quota (credential_id, throttled_until_tab, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_tab = EXCLUDED.throttled_until_tab,
    synced_at = NOW()
`

type SetAntigravityQuotaThrottledTabParams struct {
	CredentialID      string             `json:"credential_id"`
	ThrottledUntilTab pgtype.Timestamptz `json:"throttled_until_tab"`
}

func (q *Queries) SetAntigravityQuotaThrottledTab(ctx context.Context, arg SetAntigravityQuotaThrottledTabParams) error {
	_, err := q.db.Exec(ctx, setAntigravityQuotaThrottledTab, arg.CredentialID, arg.ThrottledUntilTab)
	return err
}

const upsertAntigravityQuota = `-- name: UpsertAntigravityQuota :one
INSERT INTO antigravity_quota (
    credential_id,
    quota_claude, reset_claude,
    quota_pro, reset_pro,
    quota_flash, reset_flash,
    quota_flashlite, reset_flashlite,
    quota_tab, reset_tab,
    quota_image, reset_image,
    synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    quota_claude = EXCLUDED.quota_claude,
    reset_claude = EXCLUDED.reset_claude,
    quota_pro = EXCLUDED.quota_pro,
    reset_pro = EXCLUDED.reset_pro,
    quota_flash = EXCLUDED.quota_flash,
    reset_flash = EXCLUDED.reset_flash,
    quota_flashlite = EXCLUDED.quota_flashlite,
    reset_flashlite = EXCLUDED.reset_flashlite,
    quota_tab = EXCLUDED.quota_tab,
    reset_tab = EXCLUDED.reset_tab,
    quota_image = EXCLUDED.quota_image,
    reset_image = EXCLUDED.reset_image,
    synced_at = NOW()
RETURNING credential_id, quota_claude, reset_claude, quota_pro, reset_pro, quota_flash, reset_flash, quota_flashlite, reset_flashlite, quota_tab, reset_tab, quota_image, reset_image, throttled_until_claude, throttled_until_pro, throttled_until_flash, throttled_until_flashlite, throttled_until_tab, throttled_until_image, synced_at
`

type UpsertAntigravityQuotaParams struct {
	CredentialID   string             `json:"credential_id"`
	QuotaClaude    float64            `json:"quota_claude"`
	ResetClaude    pgtype.Timestamptz `json:"reset_claude"`
	QuotaPro       float64            `json:"quota_pro"`
	ResetPro       pgtype.Timestamptz `json:"reset_pro"`
	QuotaFlash     float64            `json:"quota_flash"`
	ResetFlash     pgtype.Timestamptz `json:"reset_flash"`
	QuotaFlashlite float64            `json:"quota_flashlite"`
	ResetFlashlite pgtype.Timestamptz `json:"reset_flashlite"`
	QuotaTab       float64            `json:"quota_tab"`
	ResetTab       pgtype.Timestamptz `json:"reset_tab"`
	QuotaImage     float64            `json:"quota_image"`
	ResetImage     pgtype.Timestamptz `json:"reset_image"`
}

func (q *Queries) UpsertAntigravityQuota(ctx context.Context, arg UpsertAntigravityQuotaParams) (AntigravityQuotum, error) {
	row := q.db.QueryRow(ctx, upsertAntigravityQuota,
		arg.CredentialID,
		arg.QuotaClaude,
		arg.ResetClaude,
		arg.QuotaPro,
		arg.ResetPro,
		arg.QuotaFlash,
		arg.ResetFlash,
		arg.QuotaFlashlite,
		arg.ResetFlashlite,
		arg.QuotaTab,
		arg.ResetTab,
		arg.QuotaImage,
		arg.ResetImage,
	)
	var i AntigravityQuotum
	err := row.Scan(
		&i.CredentialID,
		&i.QuotaClaude,
		&i.ResetClaude,
		&i.QuotaPro,
		&i.ResetPro,
		&i.QuotaFlash,
		&i.ResetFlash,
		&i.QuotaFlashlite,
		&i.ResetFlashlite,
		&i.QuotaTab,
		&i.ResetTab,
		&i.QuotaImage,
		&i.ResetImage,
		&i.ThrottledUntilClaude,
		&i.ThrottledUntilPro,
		&i.ThrottledUntilFlash,
		&i.ThrottledUntilFlashlite,
		&i.ThrottledUntilTab,
		&i.ThrottledUntilImage,
		&i.SyncedAt,
	)
	return i, err
}
