// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: antigravity.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAntigravity = `-- name: CountAntigravity :one
SELECT COUNT(*) FROM antigravity
`

func (q *Queries) CountAntigravity(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAntigravity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAntigravityFiltered = `-- name: CountAntigravityFiltered :one
SELECT COUNT(*)
FROM antigravity a
LEFT JOIN antigravity_quota q ON q.credential_id = a.id
WHERE
    ($1 = '' OR LOWER(a.id) LIKE $1 OR LOWER(a.email) LIKE $1 OR LOWER(a.status) LIKE $1 OR LOWER(a.plan_type) LIKE $1)
    AND (
        $2 = ''
        OR (
            (strpos(',' || $2 || ',', ',enabled,') = 0 OR a.status = 'enabled')
            AND (strpos(',' || $2 || ',', ',disabled,') = 0 OR a.status = 'disabled')
            AND (strpos(',' || $2 || ',', ',throttled:all,') = 0 OR q.throttled_until_claude > NOW() OR q.throttled_until_pro > NOW() OR q.throttled_until_flash > NOW() OR q.throttled_until_flashlite > NOW() OR q.throttled_until_tab > NOW() OR q.throttled_until_image > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:claude,') = 0 OR q.throttled_until_claude > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:pro,') = 0 OR q.throttled_until_pro > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:flash,') = 0 OR q.throttled_until_flash > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:flashlite,') = 0 OR q.throttled_until_flashlite > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:tab,') = 0 OR q.throttled_until_tab > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:image,') = 0 OR q.throttled_until_image > NOW())
        )
    )
    AND ($3 = '' OR LOWER(a.plan_type) = LOWER($3))
    AND ($4 = false OR q.synced_at IS NULL OR q.synced_at <= '0001-01-01'::timestamptz)
`

type CountAntigravityFilteredParams struct {
	Search       interface{} `json:"search"`
	Statuses     interface{} `json:"statuses"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
}

func (q *Queries) CountAntigravityFiltered(ctx context.Context, arg CountAntigravityFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAntigravityFiltered,
		arg.Search,
		arg.Statuses,
		arg.PlanType,
		arg.UnsyncedOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledAntigravity = `-- name: CountEnabledAntigravity :one
SELECT COUNT(*)
FROM antigravity
WHERE status = 'enabled'
`

func (q *Queries) CountEnabledAntigravity(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledAntigravity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAntigravity = `-- name: DeleteAntigravity :execrows
DELETE FROM antigravity WHERE id = $1
`

func (q *Queries) DeleteAntigravity(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAntigravity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAntigravity = `-- name: GetAntigravity :one
SELECT id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
FROM antigravity
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAntigravity(ctx context.Context, id string) (Antigravity, error) {
	row := q.db.QueryRow(ctx, getAntigravity, id)
	var i Antigravity
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const listAntigravity = `-- name: ListAntigravity :many
SELECT
    a.id, a.status, a.access_token, a.refresh_token, a.expired,
    a.email, a.project_id, a.plan_type, a.reason,
    COALESCE(q.quota_claude, 1.0) AS quota_claude,
    COALESCE(q.reset_claude, NOW()) AS reset_claude,
    COALESCE(q.quota_pro, 1.0) AS quota_pro,
    COALESCE(q.reset_pro, NOW()) AS reset_pro,
    COALESCE(q.quota_flash, 1.0) AS quota_flash,
    COALESCE(q.reset_flash, NOW()) AS reset_flash,
    COALESCE(q.quota_flashlite, 1.0) AS quota_flashlite,
    COALESCE(q.reset_flashlite, NOW()) AS reset_flashlite,
    COALESCE(q.quota_tab, 1.0) AS quota_tab,
    COALESCE(q.reset_tab, NOW() + INTERVAL '100 years') AS reset_tab,
    COALESCE(q.quota_image, 1.0) AS quota_image,
    COALESCE(q.reset_image, NOW()) AS reset_image,
    COALESCE(c.credits_amount, 0) AS credits_amount,
    COALESCE(c.credit_types, '') AS credit_types,
    COALESCE(q.throttled_until_claude, '0001-01-01'::timestamptz) AS throttled_until_claude,
    COALESCE(q.throttled_until_pro, '0001-01-01'::timestamptz) AS throttled_until_pro,
    COALESCE(q.throttled_until_flash, '0001-01-01'::timestamptz) AS throttled_until_flash,
    COALESCE(q.throttled_until_flashlite, '0001-01-01'::timestamptz) AS throttled_until_flashlite,
    COALESCE(q.throttled_until_tab, '0001-01-01'::timestamptz) AS throttled_until_tab,
    COALESCE(q.throttled_until_image, '0001-01-01'::timestamptz) AS throttled_until_image,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM antigravity a
LEFT JOIN antigravity_quota q ON q.credential_id = a.id
LEFT JOIN antigravity_credits c ON c.credential_id = a.id
ORDER BY a.id
`

type ListAntigravityRow struct {
	ID                      string             `json:"id"`
	Status                  string             `json:"status"`
	AccessToken             string             `json:"access_token"`
	RefreshToken            string             `json:"refresh_token"`
	Expired                 pgtype.Timestamptz `json:"expired"`
	Email                   string             `json:"email"`
	ProjectID               string             `json:"project_id"`
	PlanType                string             `json:"plan_type"`
	Reason                  string             `json:"reason"`
	QuotaClaude             float64            `json:"quota_claude"`
	ResetClaude             pgtype.Timestamptz `json:"reset_claude"`
	QuotaPro                float64            `json:"quota_pro"`
	ResetPro                pgtype.Timestamptz `json:"reset_pro"`
	QuotaFlash              float64            `json:"quota_flash"`
	ResetFlash              pgtype.Timestamptz `json:"reset_flash"`
	QuotaFlashlite          float64            `json:"quota_flashlite"`
	ResetFlashlite          pgtype.Timestamptz `json:"reset_flashlite"`
	QuotaTab                float64            `json:"quota_tab"`
	ResetTab                pgtype.Timestamptz `json:"reset_tab"`
	QuotaImage              float64            `json:"quota_image"`
	ResetImage              pgtype.Timestamptz `json:"reset_image"`
	CreditsAmount           float64            `json:"credits_amount"`
	CreditTypes             string             `json:"credit_types"`
	ThrottledUntilClaude    pgtype.Timestamptz `json:"throttled_until_claude"`
	ThrottledUntilPro       pgtype.Timestamptz `json:"throttled_until_pro"`
	ThrottledUntilFlash     pgtype.Timestamptz `json:"throttled_until_flash"`
	ThrottledUntilFlashlite pgtype.Timestamptz `json:"throttled_until_flashlite"`
	ThrottledUntilTab       pgtype.Timestamptz `json:"throttled_until_tab"`
	ThrottledUntilImage     pgtype.Timestamptz `json:"throttled_until_image"`
	SyncedAt                pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListAntigravity(ctx context.Context) ([]ListAntigravityRow, error) {
	rows, err := q.db.Query(ctx, listAntigravity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAntigravityRow{}
	for rows.Next() {
		var i ListAntigravityRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Expired,
			&i.Email,
			&i.ProjectID,
			&i.PlanType,
			&i.Reason,
			&i.QuotaClaude,
			&i.ResetClaude,
			&i.QuotaPro,
			&i.ResetPro,
			&i.QuotaFlash,
			&i.ResetFlash,
			&i.QuotaFlashlite,
			&i.ResetFlashlite,
			&i.QuotaTab,
			&i.ResetTab,
			&i.QuotaImage,
			&i.ResetImage,
			&i.CreditsAmount,
			&i.CreditTypes,
			&i.ThrottledUntilClaude,
			&i.ThrottledUntilPro,
			&i.ThrottledUntilFlash,
			&i.ThrottledUntilFlashlite,
			&i.ThrottledUntilTab,
			&i.ThrottledUntilImage,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAntigravityPaged = `-- name: ListAntigravityPaged :many
SELECT
    a.id, a.status, a.access_token, a.refresh_token, a.expired,
    a.email, a.project_id, a.plan_type, a.reason,
    COALESCE(q.quota_claude, 1.0) AS quota_claude,
    COALESCE(q.reset_claude, NOW()) AS reset_claude,
    COALESCE(q.quota_pro, 1.0) AS quota_pro,
    COALESCE(q.reset_pro, NOW()) AS reset_pro,
    COALESCE(q.quota_flash, 1.0) AS quota_flash,
    COALESCE(q.reset_flash, NOW()) AS reset_flash,
    COALESCE(q.quota_flashlite, 1.0) AS quota_flashlite,
    COALESCE(q.reset_flashlite, NOW()) AS reset_flashlite,
    COALESCE(q.quota_tab, 1.0) AS quota_tab,
    COALESCE(q.reset_tab, NOW() + INTERVAL '100 years') AS reset_tab,
    COALESCE(q.quota_image, 1.0) AS quota_image,
    COALESCE(q.reset_image, NOW()) AS reset_image,
    COALESCE(c.credits_amount, 0) AS credits_amount,
    COALESCE(c.credit_types, '') AS credit_types,
    COALESCE(q.throttled_until_claude, '0001-01-01'::timestamptz) AS throttled_until_claude,
    COALESCE(q.throttled_until_pro, '0001-01-01'::timestamptz) AS throttled_until_pro,
    COALESCE(q.throttled_until_flash, '0001-01-01'::timestamptz) AS throttled_until_flash,
    COALESCE(q.throttled_until_flashlite, '0001-01-01'::timestamptz) AS throttled_until_flashlite,
    COALESCE(q.throttled_until_tab, '0001-01-01'::timestamptz) AS throttled_until_tab,
    COALESCE(q.throttled_until_image, '0001-01-01'::timestamptz) AS throttled_until_image,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM antigravity a
LEFT JOIN antigravity_quota q ON q.credential_id = a.id
LEFT JOIN antigravity_credits c ON c.credential_id = a.id
WHERE
    ($1 = '' OR LOWER(a.id) LIKE $1 OR LOWER(a.email) LIKE $1 OR LOWER(a.status) LIKE $1 OR LOWER(a.plan_type) LIKE $1)
    AND (
        $2 = ''
        OR (
            (strpos(',' || $2 || ',', ',enabled,') = 0 OR a.status = 'enabled')
            AND (strpos(',' || $2 || ',', ',disabled,') = 0 OR a.status = 'disabled')
            AND (strpos(',' || $2 || ',', ',throttled:all,') = 0 OR q.throttled_until_claude > NOW() OR q.throttled_until_pro > NOW() OR q.throttled_until_flash > NOW() OR q.throttled_until_flashlite > NOW() OR q.throttled_until_tab > NOW() OR q.throttled_until_image > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:claude,') = 0 OR q.throttled_until_claude > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:pro,') = 0 OR q.throttled_until_pro > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:flash,') = 0 OR q.throttled_until_flash > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:flashlite,') = 0 OR q.throttled_until_flashlite > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:tab,') = 0 OR q.throttled_until_tab > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:image,') = 0 OR q.throttled_until_image > NOW())
        )
    )
    AND ($3 = '' OR LOWER(a.plan_type) = LOWER($3))
    AND ($4 = false OR q.synced_at IS NULL OR q.synced_at <= '0001-01-01'::timestamptz)
ORDER BY a.id
LIMIT $6 OFFSET $5
`

type ListAntigravityPagedParams struct {
	Search       interface{} `json:"search"`
	Statuses     interface{} `json:"statuses"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

type ListAntigravityPagedRow struct {
	ID                      string             `json:"id"`
	Status                  string             `json:"status"`
	AccessToken             string             `json:"access_token"`
	RefreshToken            string             `json:"refresh_token"`
	Expired                 pgtype.Timestamptz `json:"expired"`
	Email                   string             `json:"email"`
	ProjectID               string             `json:"project_id"`
	PlanType                string             `json:"plan_type"`
	Reason                  string             `json:"reason"`
	QuotaClaude             float64            `json:"quota_claude"`
	ResetClaude             pgtype.Timestamptz `json:"reset_claude"`
	QuotaPro                float64            `json:"quota_pro"`
	ResetPro                pgtype.Timestamptz `json:"reset_pro"`
	QuotaFlash              float64            `json:"quota_flash"`
	ResetFlash              pgtype.Timestamptz `json:"reset_flash"`
	QuotaFlashlite          float64            `json:"quota_flashlite"`
	ResetFlashlite          pgtype.Timestamptz `json:"reset_flashlite"`
	QuotaTab                float64            `json:"quota_tab"`
	ResetTab                pgtype.Timestamptz `json:"reset_tab"`
	QuotaImage              float64            `json:"quota_image"`
	ResetImage              pgtype.Timestamptz `json:"reset_image"`
	CreditsAmount           float64            `json:"credits_amount"`
	CreditTypes             string             `json:"credit_types"`
	ThrottledUntilClaude    pgtype.Timestamptz `json:"throttled_until_claude"`
	ThrottledUntilPro       pgtype.Timestamptz `json:"throttled_until_pro"`
	ThrottledUntilFlash     pgtype.Timestamptz `json:"throttled_until_flash"`
	ThrottledUntilFlashlite pgtype.Timestamptz `json:"throttled_until_flashlite"`
	ThrottledUntilTab       pgtype.Timestamptz `json:"throttled_until_tab"`
	ThrottledUntilImage     pgtype.Timestamptz `json:"throttled_until_image"`
	SyncedAt                pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListAntigravityPaged(ctx context.Context, arg ListAntigravityPagedParams) ([]ListAntigravityPagedRow, error) {
	rows, err := q.db.Query(ctx, listAntigravityPaged,
		arg.Search,
		arg.Statuses,
		arg.PlanType,
		arg.UnsyncedOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAntigravityPagedRow{}
	for rows.Next() {
		var i ListAntigravityPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Expired,
			&i.Email,
			&i.ProjectID,
			&i.PlanType,
			&i.Reason,
			&i.QuotaClaude,
			&i.ResetClaude,
			&i.QuotaPro,
			&i.ResetPro,
			&i.QuotaFlash,
			&i.ResetFlash,
			&i.QuotaFlashlite,
			&i.ResetFlashlite,
			&i.QuotaTab,
			&i.ResetTab,
			&i.QuotaImage,
			&i.ResetImage,
			&i.CreditsAmount,
			&i.CreditTypes,
			&i.ThrottledUntilClaude,
			&i.ThrottledUntilPro,
			&i.ThrottledUntilFlash,
			&i.ThrottledUntilFlashlite,
			&i.ThrottledUntilTab,
			&i.ThrottledUntilImage,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAntigravityPlanTypes = `-- name: ListAntigravityPlanTypes :many
SELECT DISTINCT LOWER(TRIM(a.plan_type)) AS plan_type
FROM antigravity a
LEFT JOIN antigravity_quota q ON q.credential_id = a.id
WHERE
    ($1 = '' OR LOWER(a.id) LIKE $1 OR LOWER(a.email) LIKE $1 OR LOWER(a.status) LIKE $1 OR LOWER(a.plan_type) LIKE $1)
    AND (
        $2 = ''
        OR (
            (strpos(',' || $2 || ',', ',enabled,') = 0 OR a.status = 'enabled')
            AND (strpos(',' || $2 || ',', ',disabled,') = 0 OR a.status = 'disabled')
            AND (strpos(',' || $2 || ',', ',throttled:all,') = 0 OR q.throttled_until_claude > NOW() OR q.throttled_until_pro > NOW() OR q.throttled_until_flash > NOW() OR q.throttled_until_flashlite > NOW() OR q.throttled_until_tab > NOW() OR q.throttled_until_image > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:claude,') = 0 OR q.throttled_until_claude > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:pro,') = 0 OR q.throttled_until_pro > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:flash,') = 0 OR q.throttled_until_flash > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:flashlite,') = 0 OR q.throttled_until_flashlite > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:tab,') = 0 OR q.throttled_until_tab > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:image,') = 0 OR q.throttled_until_image > NOW())
        )
    )
    AND ($3 = false OR q.synced_at IS NULL OR q.synced_at <= '0001-01-01'::timestamptz)
    AND TRIM(a.plan_type) <> ''
ORDER BY plan_type
`

type ListAntigravityPlanTypesParams struct {
	Search       interface{} `json:"search"`
	Statuses     interface{} `json:"statuses"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
}

func (q *Queries) ListAntigravityPlanTypes(ctx context.Context, arg ListAntigravityPlanTypesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listAntigravityPlanTypes, arg.Search, arg.Statuses, arg.UnsyncedOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var plan_type string
		if err := rows.Scan(&plan_type); err != nil {
			return nil, err
		}
		items = append(items, plan_type)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAntigravityThrottleDeadline = `-- name: NextAntigravityThrottleDeadline :one
SELECT MIN(deadline)::timestamptz AS deadline
FROM (
    SELECT q.throttled_until_claude AS deadline
    FROM antigravity a
    JOIN antigravity_quota q ON q.credential_id = a.id
    WHERE a.status <> 'disabled' AND q.throttled_until_claude > NOW()
    UNION ALL
    SELECT q.throttled_until_pro AS deadline
    FROM antigravity a
    JOIN antigravity_quota q ON q.credential_id = a.id
    WHERE a.status <> 'disabled' AND q.throttled_until_pro > NOW()
    UNION ALL
    SELECT q.throttled_until_flash AS deadline
    FROM antigravity a
    JOIN antigravity_quota q ON q.credential_id = a.id
    WHERE a.status <> 'disabled' AND q.throttled_until_flash > NOW()
    UNION ALL
    SELECT q.throttled_until_flashlite AS deadline
    FROM antigravity a
    JOIN antigravity_quota q ON q.credential_id = a.id
    WHERE a.status <> 'disabled' AND q.throttled_until_flashlite > NOW()
    UNION ALL
    SELECT q.throttled_until_tab AS deadline
    FROM antigravity a
    JOIN antigravity_quota q ON q.credential_id = a.id
    WHERE a.status <> 'disabled' AND q.throttled_until_tab > NOW()
    UNION ALL
    SELECT q.throttled_until_image AS deadline
    FROM antigravity a
    JOIN antigravity_quota q ON q.credential_id = a.id
    WHERE a.status <> 'disabled' AND q.throttled_until_image > NOW()
) deadlines
`

func (q *Queries) NextAntigravityThrottleDeadline(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextAntigravityThrottleDeadline)
	var deadline pgtype.Timestamptz
	err := row.Scan(&deadline)
	return deadline, err
}

const restoreExpiredThrottledAntigravity = `-- name: RestoreExpiredThrottledAntigravity :exec
UPDATE antigravity
SET status = 'enabled', reason = ''
WHERE status = 'throttled'
`

func (q *Queries) RestoreExpiredThrottledAntigravity(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreExpiredThrottledAntigravity)
	return err
}

const updateAntigravityStatus = `-- name: UpdateAntigravityStatus :one
UPDATE antigravity
SET status = $1, reason = $2
WHERE id = $3
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpdateAntigravityStatusParams struct {
	Status string `json:"status"`
	Reason string `json:"reason"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateAntigravityStatus(ctx context.Context, arg UpdateAntigravityStatusParams) (Antigravity, error) {
	row := q.db.QueryRow(ctx, updateAntigravityStatus, arg.Status, arg.Reason, arg.ID)
	var i Antigravity
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const updateAntigravityTokens = `-- name: UpdateAntigravityTokens :one
UPDATE antigravity
SET
    status = $1,
    access_token = $2,
    refresh_token = $3,
    expired = $4,
    email = $5,
    project_id = $6,
    plan_type = $7,
    reason = '',
    synced_at = NOW()
WHERE id = $8
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpdateAntigravityTokensParams struct {
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	Email        string             `json:"email"`
	ProjectID    string             `json:"project_id"`
	PlanType     string             `json:"plan_type"`
	ID           string             `json:"id"`
}

func (q *Queries) UpdateAntigravityTokens(ctx context.Context, arg UpdateAntigravityTokensParams) (Antigravity, error) {
	row := q.db.QueryRow(ctx, updateAntigravityTokens,
		arg.Status,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expired,
		arg.Email,
		arg.ProjectID,
		arg.PlanType,
		arg.ID,
	)
	var i Antigravity
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const upsertAntigravity = `-- name: UpsertAntigravity :one
INSERT INTO antigravity (id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (id) DO UPDATE
SET
    status = EXCLUDED.status,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expired = EXCLUDED.expired,
    email = EXCLUDED.email,
    project_id = EXCLUDED.project_id,
    plan_type = EXCLUDED.plan_type,
    reason = EXCLUDED.reason,
    synced_at = NOW()
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpsertAntigravityParams struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	Email        string             `json:"email"`
	ProjectID    string             `json:"project_id"`
	PlanType     string             `json:"plan_type"`
	Reason       string             `json:"reason"`
}

func (q *Queries) UpsertAntigravity(ctx context.Context, arg UpsertAntigravityParams) (Antigravity, error) {
	row := q.db.QueryRow(ctx, upsertAntigravity,
		arg.ID,
		arg.Status,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expired,
		arg.Email,
		arg.ProjectID,
		arg.PlanType,
		arg.Reason,
	)
	var i Antigravity
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}
