// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: codex.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCodex = `-- name: CountCodex :one
SELECT COUNT(*) FROM codex
`

func (q *Queries) CountCodex(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCodex)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCodexFiltered = `-- name: CountCodexFiltered :one
SELECT COUNT(*)
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
WHERE
    ($1 = '' OR LOWER(c.id) LIKE $1 OR LOWER(c.status) LIKE $1 OR LOWER(c.plan_type) LIKE $1)
    AND ($2 = '' OR c.status = $2)
    AND ($3 = '' OR LOWER(c.plan_type) = LOWER($3))
    AND ((NOT $4::boolean) OR q.synced_at IS NULL OR q.synced_at <= '0001-01-01'::timestamptz)
`

type CountCodexFilteredParams struct {
	Search       interface{} `json:"search"`
	Status       interface{} `json:"status"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly bool        `json:"unsynced_only"`
}

func (q *Queries) CountCodexFiltered(ctx context.Context, arg CountCodexFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCodexFiltered,
		arg.Search,
		arg.Status,
		arg.PlanType,
		arg.UnsyncedOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledCodex = `-- name: CountEnabledCodex :one
SELECT COUNT(*)
FROM codex
WHERE status = 'enabled'
`

func (q *Queries) CountEnabledCodex(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledCodex)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCodex = `-- name: CreateCodex :one
INSERT INTO codex (id, status, access_token, expired, refresh_token, plan_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type CreateCodexParams struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	RefreshToken string             `json:"refresh_token"`
	PlanType     string             `json:"plan_type"`
}

func (q *Queries) CreateCodex(ctx context.Context, arg CreateCodexParams) (Codex, error) {
	row := q.db.QueryRow(ctx, createCodex,
		arg.ID,
		arg.Status,
		arg.AccessToken,
		arg.Expired,
		arg.RefreshToken,
		arg.PlanType,
	)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const deleteCodex = `-- name: DeleteCodex :execrows
DELETE FROM codex WHERE id = $1
`

func (q *Queries) DeleteCodex(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCodex, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCodex = `-- name: GetCodex :one
SELECT id, status, access_token, expired, refresh_token, plan_type, reason
FROM codex
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCodex(ctx context.Context, id string) (Codex, error) {
	row := q.db.QueryRow(ctx, getCodex, id)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const listCodex = `-- name: ListCodex :many
SELECT
    c.id, c.status, c.access_token, c.expired, c.refresh_token, c.plan_type, c.reason,
    COALESCE(q.quota_5h, 1.0) AS quota_5h,
    COALESCE(q.quota_7d, 1.0) AS quota_7d,
    COALESCE(q.quota_spark_5h, 1.0) AS quota_spark_5h,
    COALESCE(q.quota_spark_7d, 1.0) AS quota_spark_7d,
    COALESCE(q.reset_5h, '0001-01-01'::timestamptz) AS reset_5h,
    COALESCE(q.reset_7d, '0001-01-01'::timestamptz) AS reset_7d,
    COALESCE(q.reset_spark_5h, '0001-01-01'::timestamptz) AS reset_spark_5h,
    COALESCE(q.reset_spark_7d, '0001-01-01'::timestamptz) AS reset_spark_7d,
    GREATEST(COALESCE(q.throttled_until, '0001-01-01'::timestamptz), COALESCE(q.throttled_until_spark, '0001-01-01'::timestamptz))::timestamptz AS throttled_until,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
ORDER BY c.id
`

type ListCodexRow struct {
	ID             string             `json:"id"`
	Status         string             `json:"status"`
	AccessToken    string             `json:"access_token"`
	Expired        pgtype.Timestamptz `json:"expired"`
	RefreshToken   string             `json:"refresh_token"`
	PlanType       string             `json:"plan_type"`
	Reason         string             `json:"reason"`
	Quota5h        float64            `json:"quota_5h"`
	Quota7d        float64            `json:"quota_7d"`
	QuotaSpark5h   float64            `json:"quota_spark_5h"`
	QuotaSpark7d   float64            `json:"quota_spark_7d"`
	Reset5h        pgtype.Timestamptz `json:"reset_5h"`
	Reset7d        pgtype.Timestamptz `json:"reset_7d"`
	ResetSpark5h   pgtype.Timestamptz `json:"reset_spark_5h"`
	ResetSpark7d   pgtype.Timestamptz `json:"reset_spark_7d"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListCodex(ctx context.Context) ([]ListCodexRow, error) {
	rows, err := q.db.Query(ctx, listCodex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCodexRow{}
	for rows.Next() {
		var i ListCodexRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.Expired,
			&i.RefreshToken,
			&i.PlanType,
			&i.Reason,
			&i.Quota5h,
			&i.Quota7d,
			&i.QuotaSpark5h,
			&i.QuotaSpark7d,
			&i.Reset5h,
			&i.Reset7d,
			&i.ResetSpark5h,
			&i.ResetSpark7d,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodexPaged = `-- name: ListCodexPaged :many
SELECT
    c.id, c.status, c.access_token, c.expired, c.refresh_token, c.plan_type, c.reason,
    COALESCE(q.quota_5h, 1.0) AS quota_5h,
    COALESCE(q.quota_7d, 1.0) AS quota_7d,
    COALESCE(q.quota_spark_5h, 1.0) AS quota_spark_5h,
    COALESCE(q.quota_spark_7d, 1.0) AS quota_spark_7d,
    COALESCE(q.reset_5h, '0001-01-01'::timestamptz) AS reset_5h,
    COALESCE(q.reset_7d, '0001-01-01'::timestamptz) AS reset_7d,
    COALESCE(q.reset_spark_5h, '0001-01-01'::timestamptz) AS reset_spark_5h,
    COALESCE(q.reset_spark_7d, '0001-01-01'::timestamptz) AS reset_spark_7d,
    GREATEST(COALESCE(q.throttled_until, '0001-01-01'::timestamptz), COALESCE(q.throttled_until_spark, '0001-01-01'::timestamptz))::timestamptz AS throttled_until,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
WHERE
    ($1 = '' OR LOWER(c.id) LIKE $1 OR LOWER(c.status) LIKE $1 OR LOWER(c.plan_type) LIKE $1)
    AND ($2 = '' OR c.status = $2)
    AND ($3 = '' OR LOWER(c.plan_type) = LOWER($3))
    AND ((NOT $4::boolean) OR q.synced_at IS NULL OR q.synced_at <= '0001-01-01'::timestamptz)
ORDER BY c.id
LIMIT $6 OFFSET $5
`

type ListCodexPagedParams struct {
	Search       interface{} `json:"search"`
	Status       interface{} `json:"status"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly bool        `json:"unsynced_only"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCodexPagedRow struct {
	ID             string             `json:"id"`
	Status         string             `json:"status"`
	AccessToken    string             `json:"access_token"`
	Expired        pgtype.Timestamptz `json:"expired"`
	RefreshToken   string             `json:"refresh_token"`
	PlanType       string             `json:"plan_type"`
	Reason         string             `json:"reason"`
	Quota5h        float64            `json:"quota_5h"`
	Quota7d        float64            `json:"quota_7d"`
	QuotaSpark5h   float64            `json:"quota_spark_5h"`
	QuotaSpark7d   float64            `json:"quota_spark_7d"`
	Reset5h        pgtype.Timestamptz `json:"reset_5h"`
	Reset7d        pgtype.Timestamptz `json:"reset_7d"`
	ResetSpark5h   pgtype.Timestamptz `json:"reset_spark_5h"`
	ResetSpark7d   pgtype.Timestamptz `json:"reset_spark_7d"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListCodexPaged(ctx context.Context, arg ListCodexPagedParams) ([]ListCodexPagedRow, error) {
	rows, err := q.db.Query(ctx, listCodexPaged,
		arg.Search,
		arg.Status,
		arg.PlanType,
		arg.UnsyncedOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCodexPagedRow{}
	for rows.Next() {
		var i ListCodexPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.Expired,
			&i.RefreshToken,
			&i.PlanType,
			&i.Reason,
			&i.Quota5h,
			&i.Quota7d,
			&i.QuotaSpark5h,
			&i.QuotaSpark7d,
			&i.Reset5h,
			&i.Reset7d,
			&i.ResetSpark5h,
			&i.ResetSpark7d,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreExpiredThrottledCodex = `-- name: RestoreExpiredThrottledCodex :exec
UPDATE codex
SET status = 'enabled', reason = ''
WHERE status = 'throttled'
  AND id IN (
    SELECT c.id
    FROM codex c
    LEFT JOIN codex_quota q ON q.credential_id = c.id
    WHERE c.status = 'throttled'
      AND COALESCE(q.throttled_until, NOW()) <= NOW()
      AND COALESCE(q.throttled_until_spark, NOW()) <= NOW()
  )
`

func (q *Queries) RestoreExpiredThrottledCodex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreExpiredThrottledCodex)
	return err
}

const updateCodexStatus = `-- name: UpdateCodexStatus :one
UPDATE codex SET status = $2, reason = $3 WHERE id = $1
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type UpdateCodexStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
	Reason string `json:"reason"`
}

func (q *Queries) UpdateCodexStatus(ctx context.Context, arg UpdateCodexStatusParams) (Codex, error) {
	row := q.db.QueryRow(ctx, updateCodexStatus, arg.ID, arg.Status, arg.Reason)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}

const updateCodexTokens = `-- name: UpdateCodexTokens :one
UPDATE codex
SET
    status = $2,
    access_token = $3,
    expired = $4,
    refresh_token = $5,
    plan_type = $6,
    reason = ''
WHERE id = $1
RETURNING id, status, access_token, expired, refresh_token, plan_type, reason
`

type UpdateCodexTokensParams struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	RefreshToken string             `json:"refresh_token"`
	PlanType     string             `json:"plan_type"`
}

func (q *Queries) UpdateCodexTokens(ctx context.Context, arg UpdateCodexTokensParams) (Codex, error) {
	row := q.db.QueryRow(ctx, updateCodexTokens,
		arg.ID,
		arg.Status,
		arg.AccessToken,
		arg.Expired,
		arg.RefreshToken,
		arg.PlanType,
	)
	var i Codex
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.Expired,
		&i.RefreshToken,
		&i.PlanType,
		&i.Reason,
	)
	return i, err
}
