// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gemini_cli.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnabledGeminiCLI = `-- name: CountEnabledGeminiCLI :one
SELECT COUNT(*)
FROM gemini
WHERE status = 'enabled'
`

func (q *Queries) CountEnabledGeminiCLI(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledGeminiCLI)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGeminiCLI = `-- name: CountGeminiCLI :one
SELECT COUNT(*) FROM gemini
`

func (q *Queries) CountGeminiCLI(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGeminiCLI)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGeminiCLIFiltered = `-- name: CountGeminiCLIFiltered :one
SELECT COUNT(*)
FROM gemini g
LEFT JOIN gemini_quota q ON q.credential_id = g.id
WHERE
    ($1 = '' OR LOWER(g.id) LIKE $1 OR LOWER(g.email) LIKE $1 OR LOWER(g.status) LIKE $1 OR LOWER(g.plan_type) LIKE $1)
    AND ($2 = '' OR g.status = $2)
    AND ($3 = '' OR LOWER(g.plan_type) = LOWER($3))
    AND ($4 = false OR q.synced_at IS NULL OR q.synced_at <= '0001-01-01'::timestamptz)
`

type CountGeminiCLIFilteredParams struct {
	Search       interface{} `json:"search"`
	Status       interface{} `json:"status"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
}

func (q *Queries) CountGeminiCLIFiltered(ctx context.Context, arg CountGeminiCLIFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGeminiCLIFiltered,
		arg.Search,
		arg.Status,
		arg.PlanType,
		arg.UnsyncedOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGeminiCLI = `-- name: DeleteGeminiCLI :execrows
DELETE FROM gemini WHERE id = $1
`

func (q *Queries) DeleteGeminiCLI(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGeminiCLI, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGeminiCLI = `-- name: GetGeminiCLI :one
SELECT id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
FROM gemini
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGeminiCLI(ctx context.Context, id string) (Gemini, error) {
	row := q.db.QueryRow(ctx, getGeminiCLI, id)
	var i Gemini
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const listGeminiCLI = `-- name: ListGeminiCLI :many
SELECT
    g.id, g.status, g.access_token, g.refresh_token, g.expired,
    g.email, g.project_id, g.plan_type, g.reason,
    COALESCE(q.quota_pro, 1.0) AS quota_pro,
    COALESCE(q.reset_pro, NOW()) AS reset_pro,
    COALESCE(q.quota_flash, 1.0) AS quota_flash,
    COALESCE(q.reset_flash, NOW()) AS reset_flash,
    COALESCE(q.quota_flashlite, 1.0) AS quota_flashlite,
    COALESCE(q.reset_flashlite, NOW()) AS reset_flashlite,
    GREATEST(COALESCE(q.throttled_until_pro, '0001-01-01'::timestamptz), COALESCE(q.throttled_until_flash, '0001-01-01'::timestamptz), COALESCE(q.throttled_until_flashlite, '0001-01-01'::timestamptz))::timestamptz AS throttled_until,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM gemini g
LEFT JOIN gemini_quota q ON q.credential_id = g.id
ORDER BY g.id
`

type ListGeminiCLIRow struct {
	ID             string             `json:"id"`
	Status         string             `json:"status"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   string             `json:"refresh_token"`
	Expired        pgtype.Timestamptz `json:"expired"`
	Email          string             `json:"email"`
	ProjectID      string             `json:"project_id"`
	PlanType       string             `json:"plan_type"`
	Reason         string             `json:"reason"`
	QuotaPro       float64            `json:"quota_pro"`
	ResetPro       pgtype.Timestamptz `json:"reset_pro"`
	QuotaFlash     float64            `json:"quota_flash"`
	ResetFlash     pgtype.Timestamptz `json:"reset_flash"`
	QuotaFlashlite float64            `json:"quota_flashlite"`
	ResetFlashlite pgtype.Timestamptz `json:"reset_flashlite"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListGeminiCLI(ctx context.Context) ([]ListGeminiCLIRow, error) {
	rows, err := q.db.Query(ctx, listGeminiCLI)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeminiCLIRow{}
	for rows.Next() {
		var i ListGeminiCLIRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Expired,
			&i.Email,
			&i.ProjectID,
			&i.PlanType,
			&i.Reason,
			&i.QuotaPro,
			&i.ResetPro,
			&i.QuotaFlash,
			&i.ResetFlash,
			&i.QuotaFlashlite,
			&i.ResetFlashlite,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeminiCLIPaged = `-- name: ListGeminiCLIPaged :many
SELECT
    g.id, g.status, g.access_token, g.refresh_token, g.expired,
    g.email, g.project_id, g.plan_type, g.reason,
    COALESCE(q.quota_pro, 1.0) AS quota_pro,
    COALESCE(q.reset_pro, NOW()) AS reset_pro,
    COALESCE(q.quota_flash, 1.0) AS quota_flash,
    COALESCE(q.reset_flash, NOW()) AS reset_flash,
    COALESCE(q.quota_flashlite, 1.0) AS quota_flashlite,
    COALESCE(q.reset_flashlite, NOW()) AS reset_flashlite,
    GREATEST(COALESCE(q.throttled_until_pro, '0001-01-01'::timestamptz), COALESCE(q.throttled_until_flash, '0001-01-01'::timestamptz), COALESCE(q.throttled_until_flashlite, '0001-01-01'::timestamptz))::timestamptz AS throttled_until,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM gemini g
LEFT JOIN gemini_quota q ON q.credential_id = g.id
WHERE
    ($1 = '' OR LOWER(g.id) LIKE $1 OR LOWER(g.email) LIKE $1 OR LOWER(g.status) LIKE $1 OR LOWER(g.plan_type) LIKE $1)
    AND ($2 = '' OR g.status = $2)
    AND ($3 = '' OR LOWER(g.plan_type) = LOWER($3))
    AND ($4 = false OR q.synced_at IS NULL OR q.synced_at <= '0001-01-01'::timestamptz)
ORDER BY g.id
LIMIT $6 OFFSET $5
`

type ListGeminiCLIPagedParams struct {
	Search       interface{} `json:"search"`
	Status       interface{} `json:"status"`
	PlanType     interface{} `json:"plan_type"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

type ListGeminiCLIPagedRow struct {
	ID             string             `json:"id"`
	Status         string             `json:"status"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   string             `json:"refresh_token"`
	Expired        pgtype.Timestamptz `json:"expired"`
	Email          string             `json:"email"`
	ProjectID      string             `json:"project_id"`
	PlanType       string             `json:"plan_type"`
	Reason         string             `json:"reason"`
	QuotaPro       float64            `json:"quota_pro"`
	ResetPro       pgtype.Timestamptz `json:"reset_pro"`
	QuotaFlash     float64            `json:"quota_flash"`
	ResetFlash     pgtype.Timestamptz `json:"reset_flash"`
	QuotaFlashlite float64            `json:"quota_flashlite"`
	ResetFlashlite pgtype.Timestamptz `json:"reset_flashlite"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListGeminiCLIPaged(ctx context.Context, arg ListGeminiCLIPagedParams) ([]ListGeminiCLIPagedRow, error) {
	rows, err := q.db.Query(ctx, listGeminiCLIPaged,
		arg.Search,
		arg.Status,
		arg.PlanType,
		arg.UnsyncedOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeminiCLIPagedRow{}
	for rows.Next() {
		var i ListGeminiCLIPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Expired,
			&i.Email,
			&i.ProjectID,
			&i.PlanType,
			&i.Reason,
			&i.QuotaPro,
			&i.ResetPro,
			&i.QuotaFlash,
			&i.ResetFlash,
			&i.QuotaFlashlite,
			&i.ResetFlashlite,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGeminiCLIStatus = `-- name: UpdateGeminiCLIStatus :one
UPDATE gemini
SET status = $1, reason = $2
WHERE id = $3
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpdateGeminiCLIStatusParams struct {
	Status string `json:"status"`
	Reason string `json:"reason"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateGeminiCLIStatus(ctx context.Context, arg UpdateGeminiCLIStatusParams) (Gemini, error) {
	row := q.db.QueryRow(ctx, updateGeminiCLIStatus, arg.Status, arg.Reason, arg.ID)
	var i Gemini
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const updateGeminiPlanType = `-- name: UpdateGeminiPlanType :one
UPDATE gemini
SET
    plan_type = $1,
    synced_at = NOW()
WHERE id = $2
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpdateGeminiPlanTypeParams struct {
	PlanType string `json:"plan_type"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateGeminiPlanType(ctx context.Context, arg UpdateGeminiPlanTypeParams) (Gemini, error) {
	row := q.db.QueryRow(ctx, updateGeminiPlanType, arg.PlanType, arg.ID)
	var i Gemini
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const updateGeminiTokens = `-- name: UpdateGeminiTokens :one
UPDATE gemini
SET
    status = $1,
    access_token = $2,
    refresh_token = $3,
    expired = $4,
    email = $5,
    project_id = $6,
    plan_type = $7,
    reason = '',
    synced_at = NOW()
WHERE id = $8
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpdateGeminiTokensParams struct {
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	Email        string             `json:"email"`
	ProjectID    string             `json:"project_id"`
	PlanType     string             `json:"plan_type"`
	ID           string             `json:"id"`
}

func (q *Queries) UpdateGeminiTokens(ctx context.Context, arg UpdateGeminiTokensParams) (Gemini, error) {
	row := q.db.QueryRow(ctx, updateGeminiTokens,
		arg.Status,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expired,
		arg.Email,
		arg.ProjectID,
		arg.PlanType,
		arg.ID,
	)
	var i Gemini
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}

const upsertGeminiCLI = `-- name: UpsertGeminiCLI :one
INSERT INTO gemini (id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (id) DO UPDATE
SET
    status = EXCLUDED.status,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expired = EXCLUDED.expired,
    email = EXCLUDED.email,
    project_id = EXCLUDED.project_id,
    plan_type = EXCLUDED.plan_type,
    reason = EXCLUDED.reason,
    synced_at = NOW()
RETURNING id, status, access_token, refresh_token, expired, email, project_id, plan_type, reason, synced_at
`

type UpsertGeminiCLIParams struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	Email        string             `json:"email"`
	ProjectID    string             `json:"project_id"`
	PlanType     string             `json:"plan_type"`
	Reason       string             `json:"reason"`
}

func (q *Queries) UpsertGeminiCLI(ctx context.Context, arg UpsertGeminiCLIParams) (Gemini, error) {
	row := q.db.QueryRow(ctx, upsertGeminiCLI,
		arg.ID,
		arg.Status,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expired,
		arg.Email,
		arg.ProjectID,
		arg.PlanType,
		arg.Reason,
	)
	var i Gemini
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expired,
		&i.Email,
		&i.ProjectID,
		&i.PlanType,
		&i.Reason,
		&i.SyncedAt,
	)
	return i, err
}
