// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Antigravity struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	Email        string             `json:"email"`
	ProjectID    string             `json:"project_id"`
	PlanType     string             `json:"plan_type"`
	Reason       string             `json:"reason"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
}

type AntigravityCredit struct {
	CredentialID  string             `json:"credential_id"`
	CreditsAmount float64            `json:"credits_amount"`
	CreditTypes   string             `json:"credit_types"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
}

type AntigravityQuotum struct {
	CredentialID            string             `json:"credential_id"`
	QuotaClaude             float64            `json:"quota_claude"`
	ResetClaude             pgtype.Timestamptz `json:"reset_claude"`
	QuotaPro                float64            `json:"quota_pro"`
	ResetPro                pgtype.Timestamptz `json:"reset_pro"`
	QuotaFlash              float64            `json:"quota_flash"`
	ResetFlash              pgtype.Timestamptz `json:"reset_flash"`
	QuotaFlashlite          float64            `json:"quota_flashlite"`
	ResetFlashlite          pgtype.Timestamptz `json:"reset_flashlite"`
	QuotaTab                float64            `json:"quota_tab"`
	ResetTab                pgtype.Timestamptz `json:"reset_tab"`
	QuotaImage              float64            `json:"quota_image"`
	ResetImage              pgtype.Timestamptz `json:"reset_image"`
	ThrottledUntilClaude    pgtype.Timestamptz `json:"throttled_until_claude"`
	ThrottledUntilPro       pgtype.Timestamptz `json:"throttled_until_pro"`
	ThrottledUntilFlash     pgtype.Timestamptz `json:"throttled_until_flash"`
	ThrottledUntilFlashlite pgtype.Timestamptz `json:"throttled_until_flashlite"`
	ThrottledUntilTab       pgtype.Timestamptz `json:"throttled_until_tab"`
	ThrottledUntilImage     pgtype.Timestamptz `json:"throttled_until_image"`
	SyncedAt                pgtype.Timestamptz `json:"synced_at"`
}

type AuthKey struct {
	Key       string             `json:"key"`
	Role      string             `json:"role"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Codex struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	RefreshToken string             `json:"refresh_token"`
	PlanType     string             `json:"plan_type"`
	Reason       string             `json:"reason"`
}

type CodexQuotum struct {
	CredentialID        string             `json:"credential_id"`
	Quota5h             float64            `json:"quota_5h"`
	Quota7d             float64            `json:"quota_7d"`
	Quota1mo            float64            `json:"quota_1mo"`
	QuotaSpark5h        float64            `json:"quota_spark_5h"`
	QuotaSpark7d        float64            `json:"quota_spark_7d"`
	QuotaSpark1mo       float64            `json:"quota_spark_1mo"`
	Reset5h             pgtype.Timestamptz `json:"reset_5h"`
	Reset7d             pgtype.Timestamptz `json:"reset_7d"`
	Reset1mo            pgtype.Timestamptz `json:"reset_1mo"`
	ResetSpark5h        pgtype.Timestamptz `json:"reset_spark_5h"`
	ResetSpark7d        pgtype.Timestamptz `json:"reset_spark_7d"`
	ResetSpark1mo       pgtype.Timestamptz `json:"reset_spark_1mo"`
	ThrottledUntil      pgtype.Timestamptz `json:"throttled_until"`
	ThrottledUntilSpark pgtype.Timestamptz `json:"throttled_until_spark"`
	SyncedAt            pgtype.Timestamptz `json:"synced_at"`
	ResetCreditsCount   int32              `json:"reset_credits_count"`
}

type Gemini struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	Email        string             `json:"email"`
	ProjectID    string             `json:"project_id"`
	PlanType     string             `json:"plan_type"`
	Reason       string             `json:"reason"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
}

type GeminiQuotum struct {
	CredentialID            string             `json:"credential_id"`
	QuotaPro                float64            `json:"quota_pro"`
	ResetPro                pgtype.Timestamptz `json:"reset_pro"`
	QuotaFlash              float64            `json:"quota_flash"`
	ResetFlash              pgtype.Timestamptz `json:"reset_flash"`
	QuotaFlashlite          float64            `json:"quota_flashlite"`
	ResetFlashlite          pgtype.Timestamptz `json:"reset_flashlite"`
	ThrottledUntilPro       pgtype.Timestamptz `json:"throttled_until_pro"`
	ThrottledUntilFlash     pgtype.Timestamptz `json:"throttled_until_flash"`
	ThrottledUntilFlashlite pgtype.Timestamptz `json:"throttled_until_flashlite"`
	SyncedAt                pgtype.Timestamptz `json:"synced_at"`
}

type Model struct {
	Alias           string          `json:"alias"`
	Origin          string          `json:"origin"`
	Handler         string          `json:"handler"`
	PlanTypes       string          `json:"plan_types"`
	Plugin          string          `json:"plugin"`
	ContentAffinity bool            `json:"content_affinity"`
	Extra           json.RawMessage `json:"extra"`
}

type OpencodeGo struct {
	ID         string             `json:"id"`
	Status     string             `json:"status"`
	ApiKey     string             `json:"api_key"`
	AuthCookie string             `json:"auth_cookie"`
	Reason     string             `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type OpencodeGoQuotum struct {
	CredentialID   string             `json:"credential_id"`
	Quota5h        float64            `json:"quota_5h"`
	Quota7d        float64            `json:"quota_7d"`
	Quota1mo       float64            `json:"quota_1mo"`
	Reset5h        pgtype.Timestamptz `json:"reset_5h"`
	Reset7d        pgtype.Timestamptz `json:"reset_7d"`
	Reset1mo       pgtype.Timestamptz `json:"reset_1mo"`
	RewardsCount   int32              `json:"rewards_count"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
