// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthKey struct {
	Key       string             `json:"key"`
	Role      string             `json:"role"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Codex struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	RefreshToken string             `json:"refresh_token"`
	PlanType     string             `json:"plan_type"`
	Reason       string             `json:"reason"`
}

type CodexQuotum struct {
	CredentialID        string             `json:"credential_id"`
	Quota5h             float64            `json:"quota_5h"`
	Quota7d             float64            `json:"quota_7d"`
	QuotaSpark5h        float64            `json:"quota_spark_5h"`
	QuotaSpark7d        float64            `json:"quota_spark_7d"`
	Reset5h             pgtype.Timestamptz `json:"reset_5h"`
	Reset7d             pgtype.Timestamptz `json:"reset_7d"`
	ResetSpark5h        pgtype.Timestamptz `json:"reset_spark_5h"`
	ResetSpark7d        pgtype.Timestamptz `json:"reset_spark_7d"`
	ThrottledUntil      pgtype.Timestamptz `json:"throttled_until"`
	ThrottledUntilSpark pgtype.Timestamptz `json:"throttled_until_spark"`
	SyncedAt            pgtype.Timestamptz `json:"synced_at"`
}

type Gemini struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	Expired      pgtype.Timestamptz `json:"expired"`
	Email        string             `json:"email"`
	ProjectID    string             `json:"project_id"`
	PlanType     string             `json:"plan_type"`
	Reason       string             `json:"reason"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
}

type GeminiQuotum struct {
	CredentialID            string             `json:"credential_id"`
	QuotaPro                float64            `json:"quota_pro"`
	ResetPro                pgtype.Timestamptz `json:"reset_pro"`
	QuotaFlash              float64            `json:"quota_flash"`
	ResetFlash              pgtype.Timestamptz `json:"reset_flash"`
	QuotaFlashlite          float64            `json:"quota_flashlite"`
	ResetFlashlite          pgtype.Timestamptz `json:"reset_flashlite"`
	ThrottledUntilPro       pgtype.Timestamptz `json:"throttled_until_pro"`
	ThrottledUntilFlash     pgtype.Timestamptz `json:"throttled_until_flash"`
	ThrottledUntilFlashlite pgtype.Timestamptz `json:"throttled_until_flashlite"`
	SyncedAt                pgtype.Timestamptz `json:"synced_at"`
}

type Model struct {
	Alias     string          `json:"alias"`
	Origin    string          `json:"origin"`
	Handler   string          `json:"handler"`
	PlanTypes string          `json:"plan_types"`
	Extra     json.RawMessage `json:"extra"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
