// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: opencode_go.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnabledOpenCodeGo = `-- name: CountEnabledOpenCodeGo :one
SELECT COUNT(*)
FROM opencode_go
WHERE status = 'enabled'
`

func (q *Queries) CountEnabledOpenCodeGo(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledOpenCodeGo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenCodeGo = `-- name: CountOpenCodeGo :one
SELECT COUNT(*) FROM opencode_go
`

func (q *Queries) CountOpenCodeGo(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenCodeGo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenCodeGoFiltered = `-- name: CountOpenCodeGoFiltered :one
SELECT COUNT(*)
FROM opencode_go o
LEFT JOIN opencode_go_quota q ON q.credential_id = o.id
WHERE
    ($1 = '' OR LOWER(o.id) LIKE $1 OR LOWER(o.status) LIKE $1)
    AND (
        $2 = ''
        OR (
            (strpos(',' || $2 || ',', ',enabled,') = 0 OR o.status = 'enabled')
            AND (strpos(',' || $2 || ',', ',disabled,') = 0 OR o.status = 'disabled')
            AND (strpos(',' || $2 || ',', ',throttled:all,') = 0 OR q.throttled_until > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:default,') = 0 OR q.throttled_until > NOW())
        )
    )
    AND ($3 = FALSE OR q.synced_at IS NULL OR q.synced_at <= '0001-01-01'::timestamptz)
`

type CountOpenCodeGoFilteredParams struct {
	Search       interface{} `json:"search"`
	Statuses     interface{} `json:"statuses"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
}

func (q *Queries) CountOpenCodeGoFiltered(ctx context.Context, arg CountOpenCodeGoFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenCodeGoFiltered, arg.Search, arg.Statuses, arg.UnsyncedOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOpenCodeGo = `-- name: DeleteOpenCodeGo :execrows
DELETE FROM opencode_go WHERE id = $1
`

func (q *Queries) DeleteOpenCodeGo(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOpenCodeGo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOpenCodeGo = `-- name: GetOpenCodeGo :one
SELECT id, status, api_key, auth_cookie, reason, created_at, updated_at
FROM opencode_go
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOpenCodeGo(ctx context.Context, id string) (OpencodeGo, error) {
	row := q.db.QueryRow(ctx, getOpenCodeGo, id)
	var i OpencodeGo
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ApiKey,
		&i.AuthCookie,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenCodeGo = `-- name: ListOpenCodeGo :many
SELECT
    o.id, o.status, o.api_key, o.auth_cookie,
    o.reason, o.created_at, o.updated_at,
    COALESCE(q.quota_5h, 1.0)::float8 AS quota_5h,
    COALESCE(q.quota_7d, 1.0)::float8 AS quota_7d,
    COALESCE(q.quota_1mo, 1.0)::float8 AS quota_1mo,
    COALESCE(q.reset_5h, '0001-01-01'::timestamptz) AS reset_5h,
    COALESCE(q.reset_7d, '0001-01-01'::timestamptz) AS reset_7d,
    COALESCE(q.reset_1mo, '0001-01-01'::timestamptz) AS reset_1mo,
    COALESCE(q.rewards_count, 0)::int AS rewards_count,
    COALESCE(q.throttled_until, '0001-01-01'::timestamptz) AS throttled_until,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM opencode_go o
LEFT JOIN opencode_go_quota q ON q.credential_id = o.id
ORDER BY o.id
`

type ListOpenCodeGoRow struct {
	ID             string             `json:"id"`
	Status         string             `json:"status"`
	ApiKey         string             `json:"api_key"`
	AuthCookie     string             `json:"auth_cookie"`
	Reason         string             `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Quota5h        float64            `json:"quota_5h"`
	Quota7d        float64            `json:"quota_7d"`
	Quota1mo       float64            `json:"quota_1mo"`
	Reset5h        pgtype.Timestamptz `json:"reset_5h"`
	Reset7d        pgtype.Timestamptz `json:"reset_7d"`
	Reset1mo       pgtype.Timestamptz `json:"reset_1mo"`
	RewardsCount   int32              `json:"rewards_count"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListOpenCodeGo(ctx context.Context) ([]ListOpenCodeGoRow, error) {
	rows, err := q.db.Query(ctx, listOpenCodeGo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenCodeGoRow{}
	for rows.Next() {
		var i ListOpenCodeGoRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ApiKey,
			&i.AuthCookie,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Quota5h,
			&i.Quota7d,
			&i.Quota1mo,
			&i.Reset5h,
			&i.Reset7d,
			&i.Reset1mo,
			&i.RewardsCount,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCodeGoPaged = `-- name: ListOpenCodeGoPaged :many
SELECT
    o.id, o.status, o.api_key, o.auth_cookie,
    o.reason, o.created_at, o.updated_at,
    COALESCE(q.quota_5h, 1.0)::float8 AS quota_5h,
    COALESCE(q.quota_7d, 1.0)::float8 AS quota_7d,
    COALESCE(q.quota_1mo, 1.0)::float8 AS quota_1mo,
    COALESCE(q.reset_5h, '0001-01-01'::timestamptz) AS reset_5h,
    COALESCE(q.reset_7d, '0001-01-01'::timestamptz) AS reset_7d,
    COALESCE(q.reset_1mo, '0001-01-01'::timestamptz) AS reset_1mo,
    COALESCE(q.rewards_count, 0)::int AS rewards_count,
    COALESCE(q.throttled_until, '0001-01-01'::timestamptz) AS throttled_until,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM opencode_go o
LEFT JOIN opencode_go_quota q ON q.credential_id = o.id
WHERE
    ($1 = '' OR LOWER(o.id) LIKE $1 OR LOWER(o.status) LIKE $1)
    AND (
        $2 = ''
        OR (
            (strpos(',' || $2 || ',', ',enabled,') = 0 OR o.status = 'enabled')
            AND (strpos(',' || $2 || ',', ',disabled,') = 0 OR o.status = 'disabled')
            AND (strpos(',' || $2 || ',', ',throttled:all,') = 0 OR q.throttled_until > NOW())
            AND (strpos(',' || $2 || ',', ',throttled:default,') = 0 OR q.throttled_until > NOW())
        )
    )
    AND ($3 = FALSE OR q.synced_at IS NULL OR q.synced_at <= '0001-01-01'::timestamptz)
ORDER BY o.id
LIMIT $5 OFFSET $4
`

type ListOpenCodeGoPagedParams struct {
	Search       interface{} `json:"search"`
	Statuses     interface{} `json:"statuses"`
	UnsyncedOnly interface{} `json:"unsynced_only"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

type ListOpenCodeGoPagedRow struct {
	ID             string             `json:"id"`
	Status         string             `json:"status"`
	ApiKey         string             `json:"api_key"`
	AuthCookie     string             `json:"auth_cookie"`
	Reason         string             `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Quota5h        float64            `json:"quota_5h"`
	Quota7d        float64            `json:"quota_7d"`
	Quota1mo       float64            `json:"quota_1mo"`
	Reset5h        pgtype.Timestamptz `json:"reset_5h"`
	Reset7d        pgtype.Timestamptz `json:"reset_7d"`
	Reset1mo       pgtype.Timestamptz `json:"reset_1mo"`
	RewardsCount   int32              `json:"rewards_count"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListOpenCodeGoPaged(ctx context.Context, arg ListOpenCodeGoPagedParams) ([]ListOpenCodeGoPagedRow, error) {
	rows, err := q.db.Query(ctx, listOpenCodeGoPaged,
		arg.Search,
		arg.Statuses,
		arg.UnsyncedOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenCodeGoPagedRow{}
	for rows.Next() {
		var i ListOpenCodeGoPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ApiKey,
			&i.AuthCookie,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Quota5h,
			&i.Quota7d,
			&i.Quota1mo,
			&i.Reset5h,
			&i.Reset7d,
			&i.Reset1mo,
			&i.RewardsCount,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOpenCodeGoThrottleDeadline = `-- name: NextOpenCodeGoThrottleDeadline :one
SELECT MIN(q.throttled_until)::timestamptz AS deadline
FROM opencode_go o
JOIN opencode_go_quota q ON q.credential_id = o.id
WHERE o.status <> 'disabled' AND q.throttled_until > NOW()
`

func (q *Queries) NextOpenCodeGoThrottleDeadline(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextOpenCodeGoThrottleDeadline)
	var deadline pgtype.Timestamptz
	err := row.Scan(&deadline)
	return deadline, err
}

const restoreExpiredThrottledOpenCodeGo = `-- name: RestoreExpiredThrottledOpenCodeGo :exec
UPDATE opencode_go
SET status = 'enabled', reason = '', updated_at = NOW()
WHERE status = 'throttled'
`

func (q *Queries) RestoreExpiredThrottledOpenCodeGo(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreExpiredThrottledOpenCodeGo)
	return err
}

const updateOpenCodeGoStatus = `-- name: UpdateOpenCodeGoStatus :one
UPDATE opencode_go
SET status = $1, reason = $2, updated_at = NOW()
WHERE id = $3
RETURNING id, status, api_key, auth_cookie, reason, created_at, updated_at
`

type UpdateOpenCodeGoStatusParams struct {
	Status string `json:"status"`
	Reason string `json:"reason"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateOpenCodeGoStatus(ctx context.Context, arg UpdateOpenCodeGoStatusParams) (OpencodeGo, error) {
	row := q.db.QueryRow(ctx, updateOpenCodeGoStatus, arg.Status, arg.Reason, arg.ID)
	var i OpencodeGo
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ApiKey,
		&i.AuthCookie,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOpenCodeGo = `-- name: UpsertOpenCodeGo :one
INSERT INTO opencode_go (id, status, api_key, auth_cookie, reason, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (id) DO UPDATE
SET
    status = EXCLUDED.status,
    api_key = EXCLUDED.api_key,
    auth_cookie = EXCLUDED.auth_cookie,
    reason = EXCLUDED.reason,
    updated_at = NOW()
RETURNING id, status, api_key, auth_cookie, reason, created_at, updated_at
`

type UpsertOpenCodeGoParams struct {
	ID         string `json:"id"`
	Status     string `json:"status"`
	ApiKey     string `json:"api_key"`
	AuthCookie string `json:"auth_cookie"`
	Reason     string `json:"reason"`
}

func (q *Queries) UpsertOpenCodeGo(ctx context.Context, arg UpsertOpenCodeGoParams) (OpencodeGo, error) {
	row := q.db.QueryRow(ctx, upsertOpenCodeGo,
		arg.ID,
		arg.Status,
		arg.ApiKey,
		arg.AuthCookie,
		arg.Reason,
	)
	var i OpencodeGo
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ApiKey,
		&i.AuthCookie,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
