// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: opencode_go_quota.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearOpenCodeGoQuotaThrottle = `-- name: ClearOpenCodeGoQuotaThrottle :exec
INSERT INTO opencode_go_quota (credential_id, throttled_until, synced_at)
VALUES ($1, NOW(), NOW())
ON CONFLICT (credential_id) DO UPDATE
SET throttled_until = NOW()
`

func (q *Queries) ClearOpenCodeGoQuotaThrottle(ctx context.Context, credentialID string) error {
	_, err := q.db.Exec(ctx, clearOpenCodeGoQuotaThrottle, credentialID)
	return err
}

const deleteOpenCodeGoQuota = `-- name: DeleteOpenCodeGoQuota :execrows
DELETE FROM opencode_go_quota WHERE credential_id = $1
`

func (q *Queries) DeleteOpenCodeGoQuota(ctx context.Context, credentialID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOpenCodeGoQuota, credentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAvailableOpenCodeGo = `-- name: ListAvailableOpenCodeGo :many
SELECT
    o.id,
    o.auth_cookie,
    COALESCE(q.quota_5h, 1.0)::float8 AS quota_5h,
    COALESCE(q.quota_7d, 1.0)::float8 AS quota_7d,
    COALESCE(q.quota_1mo, 1.0)::float8 AS quota_1mo,
    COALESCE(q.reset_5h, '0001-01-01'::timestamptz) AS reset_5h,
    COALESCE(q.reset_7d, '0001-01-01'::timestamptz) AS reset_7d,
    COALESCE(q.reset_1mo, '0001-01-01'::timestamptz) AS reset_1mo,
    COALESCE(q.rewards_count, 0)::int AS rewards_count,
    COALESCE(q.throttled_until, '0001-01-01'::timestamptz) AS throttled_until,
    COALESCE(q.synced_at, o.created_at) AS synced_at
FROM opencode_go o
LEFT JOIN opencode_go_quota q ON q.credential_id = o.id
WHERE o.status = 'enabled'
ORDER BY
    COALESCE(q.quota_5h, 1.0) DESC,
    COALESCE(q.quota_7d, 1.0) DESC,
    COALESCE(q.quota_1mo, 1.0) DESC,
    o.id
`

type ListAvailableOpenCodeGoRow struct {
	ID             string             `json:"id"`
	AuthCookie     string             `json:"auth_cookie"`
	Quota5h        float64            `json:"quota_5h"`
	Quota7d        float64            `json:"quota_7d"`
	Quota1mo       float64            `json:"quota_1mo"`
	Reset5h        pgtype.Timestamptz `json:"reset_5h"`
	Reset7d        pgtype.Timestamptz `json:"reset_7d"`
	Reset1mo       pgtype.Timestamptz `json:"reset_1mo"`
	RewardsCount   int32              `json:"rewards_count"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListAvailableOpenCodeGo(ctx context.Context) ([]ListAvailableOpenCodeGoRow, error) {
	rows, err := q.db.Query(ctx, listAvailableOpenCodeGo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableOpenCodeGoRow{}
	for rows.Next() {
		var i ListAvailableOpenCodeGoRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthCookie,
			&i.Quota5h,
			&i.Quota7d,
			&i.Quota1mo,
			&i.Reset5h,
			&i.Reset7d,
			&i.Reset1mo,
			&i.RewardsCount,
			&i.ThrottledUntil,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOpenCodeGoQuotaThrottled = `-- name: SetOpenCodeGoQuotaThrottled :exec
INSERT INTO opencode_go_quota (credential_id, throttled_until, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET throttled_until = EXCLUDED.throttled_until
`

type SetOpenCodeGoQuotaThrottledParams struct {
	CredentialID   string             `json:"credential_id"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
}

func (q *Queries) SetOpenCodeGoQuotaThrottled(ctx context.Context, arg SetOpenCodeGoQuotaThrottledParams) error {
	_, err := q.db.Exec(ctx, setOpenCodeGoQuotaThrottled, arg.CredentialID, arg.ThrottledUntil)
	return err
}

const upsertOpenCodeGoQuota = `-- name: UpsertOpenCodeGoQuota :one
INSERT INTO opencode_go_quota (
    credential_id, quota_5h, quota_7d, quota_1mo,
    reset_5h, reset_7d, reset_1mo,
    rewards_count, synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    quota_5h = EXCLUDED.quota_5h,
    quota_7d = EXCLUDED.quota_7d,
    quota_1mo = EXCLUDED.quota_1mo,
    reset_5h = EXCLUDED.reset_5h,
    reset_7d = EXCLUDED.reset_7d,
    reset_1mo = EXCLUDED.reset_1mo,
    rewards_count = EXCLUDED.rewards_count,
    synced_at = NOW()
RETURNING credential_id, quota_5h, quota_7d, quota_1mo, reset_5h, reset_7d, reset_1mo, rewards_count, throttled_until, synced_at
`

type UpsertOpenCodeGoQuotaParams struct {
	CredentialID string             `json:"credential_id"`
	Quota5h      float64            `json:"quota_5h"`
	Quota7d      float64            `json:"quota_7d"`
	Quota1mo     float64            `json:"quota_1mo"`
	Reset5h      pgtype.Timestamptz `json:"reset_5h"`
	Reset7d      pgtype.Timestamptz `json:"reset_7d"`
	Reset1mo     pgtype.Timestamptz `json:"reset_1mo"`
	RewardsCount int32              `json:"rewards_count"`
}

func (q *Queries) UpsertOpenCodeGoQuota(ctx context.Context, arg UpsertOpenCodeGoQuotaParams) (OpencodeGoQuotum, error) {
	row := q.db.QueryRow(ctx, upsertOpenCodeGoQuota,
		arg.CredentialID,
		arg.Quota5h,
		arg.Quota7d,
		arg.Quota1mo,
		arg.Reset5h,
		arg.Reset7d,
		arg.Reset1mo,
		arg.RewardsCount,
	)
	var i OpencodeGoQuotum
	err := row.Scan(
		&i.CredentialID,
		&i.Quota5h,
		&i.Quota7d,
		&i.Quota1mo,
		&i.Reset5h,
		&i.Reset7d,
		&i.Reset1mo,
		&i.RewardsCount,
		&i.ThrottledUntil,
		&i.SyncedAt,
	)
	return i, err
}
