// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearQuotaThrottle = `-- name: ClearQuotaThrottle :exec
INSERT INTO codex_quota (credential_id, throttled_until, throttled_until_spark, synced_at)
VALUES ($1, NOW(), NOW(), NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until = NOW(),
    throttled_until_spark = NOW(),
    synced_at = NOW()
`

// Clears all tier throttles for a credential by moving them to now.
func (q *Queries) ClearQuotaThrottle(ctx context.Context, credentialID string) error {
	_, err := q.db.Exec(ctx, clearQuotaThrottle, credentialID)
	return err
}

const deleteQuota = `-- name: DeleteQuota :execrows
DELETE FROM codex_quota WHERE credential_id = $1
`

// Deletes the quota record for a credential.
func (q *Queries) DeleteQuota(ctx context.Context, credentialID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuota, credentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQuota = `-- name: GetQuota :one
SELECT credential_id, quota_5h, quota_7d, quota_spark_5h, quota_spark_7d, reset_5h, reset_7d, reset_spark_5h, reset_spark_7d, throttled_until, throttled_until_spark, synced_at FROM codex_quota WHERE credential_id = $1 LIMIT 1
`

func (q *Queries) GetQuota(ctx context.Context, credentialID string) (CodexQuotum, error) {
	row := q.db.QueryRow(ctx, getQuota, credentialID)
	var i CodexQuotum
	err := row.Scan(
		&i.CredentialID,
		&i.Quota5h,
		&i.Quota7d,
		&i.QuotaSpark5h,
		&i.QuotaSpark7d,
		&i.Reset5h,
		&i.Reset7d,
		&i.ResetSpark5h,
		&i.ResetSpark7d,
		&i.ThrottledUntil,
		&i.ThrottledUntilSpark,
		&i.SyncedAt,
	)
	return i, err
}

const listAvailableCodex = `-- name: ListAvailableCodex :many
SELECT
    c.id,
    c.plan_type,
    COALESCE(q.quota_5h, 1.0)          AS quota_5h,
    COALESCE(q.quota_7d, 1.0)          AS quota_7d,
    COALESCE(q.quota_spark_5h, 1.0)    AS quota_spark_5h,
    COALESCE(q.quota_spark_7d, 1.0)    AS quota_spark_7d,
    COALESCE(q.reset_5h, '0001-01-01'::timestamptz)        AS reset_5h,
    COALESCE(q.reset_7d, '0001-01-01'::timestamptz)        AS reset_7d,
    COALESCE(q.reset_spark_5h, '0001-01-01'::timestamptz)  AS reset_spark_5h,
    COALESCE(q.reset_spark_7d, '0001-01-01'::timestamptz)  AS reset_spark_7d,
    COALESCE(q.throttled_until, NOW()) AS throttled_until,
    COALESCE(q.throttled_until_spark, NOW()) AS throttled_until_spark,
    COALESCE(q.synced_at, '0001-01-01'::timestamptz) AS synced_at
FROM codex c
LEFT JOIN codex_quota q ON q.credential_id = c.id
WHERE c.status = 'enabled'
  AND (c.expired > NOW() OR c.refresh_token != '')
ORDER BY
    COALESCE(q.quota_5h, 1.0) DESC,
    COALESCE(q.quota_7d, 1.0) DESC
`

type ListAvailableCodexRow struct {
	ID                  string             `json:"id"`
	PlanType            string             `json:"plan_type"`
	Quota5h             float64            `json:"quota_5h"`
	Quota7d             float64            `json:"quota_7d"`
	QuotaSpark5h        float64            `json:"quota_spark_5h"`
	QuotaSpark7d        float64            `json:"quota_spark_7d"`
	Reset5h             pgtype.Timestamptz `json:"reset_5h"`
	Reset7d             pgtype.Timestamptz `json:"reset_7d"`
	ResetSpark5h        pgtype.Timestamptz `json:"reset_spark_5h"`
	ResetSpark7d        pgtype.Timestamptz `json:"reset_spark_7d"`
	ThrottledUntil      pgtype.Timestamptz `json:"throttled_until"`
	ThrottledUntilSpark pgtype.Timestamptz `json:"throttled_until_spark"`
	SyncedAt            pgtype.Timestamptz `json:"synced_at"`
}

// Returns enabled, non-throttled, non-expired credentials
// ordered by highest remaining quota ratio first.
func (q *Queries) ListAvailableCodex(ctx context.Context) ([]ListAvailableCodexRow, error) {
	rows, err := q.db.Query(ctx, listAvailableCodex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableCodexRow{}
	for rows.Next() {
		var i ListAvailableCodexRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanType,
			&i.Quota5h,
			&i.Quota7d,
			&i.QuotaSpark5h,
			&i.QuotaSpark7d,
			&i.Reset5h,
			&i.Reset7d,
			&i.ResetSpark5h,
			&i.ResetSpark7d,
			&i.ThrottledUntil,
			&i.ThrottledUntilSpark,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setQuotaThrottled = `-- name: SetQuotaThrottled :exec
INSERT INTO codex_quota (credential_id, throttled_until, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until = EXCLUDED.throttled_until,
    synced_at = NOW()
`

type SetQuotaThrottledParams struct {
	CredentialID   string             `json:"credential_id"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
}

// Sets the default tier throttle for a credential.
func (q *Queries) SetQuotaThrottled(ctx context.Context, arg SetQuotaThrottledParams) error {
	_, err := q.db.Exec(ctx, setQuotaThrottled, arg.CredentialID, arg.ThrottledUntil)
	return err
}

const setQuotaThrottledAll = `-- name: SetQuotaThrottledAll :exec
INSERT INTO codex_quota (credential_id, throttled_until, throttled_until_spark, synced_at)
VALUES ($1, $2, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until = EXCLUDED.throttled_until,
    throttled_until_spark = EXCLUDED.throttled_until_spark,
    synced_at = NOW()
`

type SetQuotaThrottledAllParams struct {
	CredentialID   string             `json:"credential_id"`
	ThrottledUntil pgtype.Timestamptz `json:"throttled_until"`
}

// Sets all tier throttles for a credential (non-tier-specific backoff).
func (q *Queries) SetQuotaThrottledAll(ctx context.Context, arg SetQuotaThrottledAllParams) error {
	_, err := q.db.Exec(ctx, setQuotaThrottledAll, arg.CredentialID, arg.ThrottledUntil)
	return err
}

const setQuotaThrottledSpark = `-- name: SetQuotaThrottledSpark :exec
INSERT INTO codex_quota (credential_id, throttled_until_spark, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    throttled_until_spark = EXCLUDED.throttled_until_spark,
    synced_at = NOW()
`

type SetQuotaThrottledSparkParams struct {
	CredentialID        string             `json:"credential_id"`
	ThrottledUntilSpark pgtype.Timestamptz `json:"throttled_until_spark"`
}

// Sets the spark tier throttle for a credential.
func (q *Queries) SetQuotaThrottledSpark(ctx context.Context, arg SetQuotaThrottledSparkParams) error {
	_, err := q.db.Exec(ctx, setQuotaThrottledSpark, arg.CredentialID, arg.ThrottledUntilSpark)
	return err
}

const upsertQuota = `-- name: UpsertQuota :one
INSERT INTO codex_quota (credential_id, quota_5h, quota_7d, quota_spark_5h, quota_spark_7d, reset_5h, reset_7d, reset_spark_5h, reset_spark_7d, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (credential_id) DO UPDATE
SET
    quota_5h      = EXCLUDED.quota_5h,
    quota_7d      = EXCLUDED.quota_7d,
    quota_spark_5h = EXCLUDED.quota_spark_5h,
    quota_spark_7d = EXCLUDED.quota_spark_7d,
    reset_5h      = EXCLUDED.reset_5h,
    reset_7d      = EXCLUDED.reset_7d,
    reset_spark_5h = EXCLUDED.reset_spark_5h,
    reset_spark_7d = EXCLUDED.reset_spark_7d,
    synced_at     = NOW()
RETURNING credential_id, quota_5h, quota_7d, quota_spark_5h, quota_spark_7d, reset_5h, reset_7d, reset_spark_5h, reset_spark_7d, throttled_until, throttled_until_spark, synced_at
`

type UpsertQuotaParams struct {
	CredentialID string             `json:"credential_id"`
	Quota5h      float64            `json:"quota_5h"`
	Quota7d      float64            `json:"quota_7d"`
	QuotaSpark5h float64            `json:"quota_spark_5h"`
	QuotaSpark7d float64            `json:"quota_spark_7d"`
	Reset5h      pgtype.Timestamptz `json:"reset_5h"`
	Reset7d      pgtype.Timestamptz `json:"reset_7d"`
	ResetSpark5h pgtype.Timestamptz `json:"reset_spark_5h"`
	ResetSpark7d pgtype.Timestamptz `json:"reset_spark_7d"`
}

// Syncs remaining quota ratios and reset timestamps from upstream.
func (q *Queries) UpsertQuota(ctx context.Context, arg UpsertQuotaParams) (CodexQuotum, error) {
	row := q.db.QueryRow(ctx, upsertQuota,
		arg.CredentialID,
		arg.Quota5h,
		arg.Quota7d,
		arg.QuotaSpark5h,
		arg.QuotaSpark7d,
		arg.Reset5h,
		arg.Reset7d,
		arg.ResetSpark5h,
		arg.ResetSpark7d,
	)
	var i CodexQuotum
	err := row.Scan(
		&i.CredentialID,
		&i.Quota5h,
		&i.Quota7d,
		&i.QuotaSpark5h,
		&i.QuotaSpark7d,
		&i.Reset5h,
		&i.Reset7d,
		&i.ResetSpark5h,
		&i.ResetSpark7d,
		&i.ThrottledUntil,
		&i.ThrottledUntilSpark,
		&i.SyncedAt,
	)
	return i, err
}
